using System;
namespace LitmusWeb.Models
{
    public class LedgerDataModel
    {
        public int id { get; set; }
        public Nullable<int> unit_code { get; set; }
        public Nullable<int> season_code { get; set; }
        public Nullable<System.DateTime> trans_date { get; set; }
        public Nullable<decimal> cane_crushed { get; set; }
        public Nullable<decimal> gross_mixed_juice_qtl { get; set; }
        public Nullable<decimal> gross_mixed_juice_percent_cane { get; set; }
        public Nullable<decimal> dirt_correction_qtl { get; set; }
        public Nullable<decimal> dirt_correction_perccent_cane { get; set; }
        public Nullable<decimal> net_mixed_juice_qtl { get; set; }
        public Nullable<decimal> net_mixed_juice_percent_cane { get; set; }
        public Nullable<decimal> total_water { get; set; }
        public Nullable<decimal> water_percent_cane { get; set; }
        public Nullable<decimal> total_bagasse_qtl { get; set; }
        public Nullable<decimal> total_bagasse_percent_cane { get; set; }
        public Nullable<decimal> press_cake { get; set; }
        public Nullable<decimal> press_cake_percent_cane { get; set; }
        public Nullable<decimal> pol_in_mixed_juice_qtl { get; set; }
        public Nullable<decimal> combined_pol_mixed_juice_avg { get; set; }
        public Nullable<decimal> pol_in_mixed_juice_percent_cane { get; set; }
        public Nullable<decimal> brix_in_mixed_juice { get; set; }
        public Nullable<decimal> brix_in_mixed_juice_percentage_cane { get; set; }
        public Nullable<decimal> non_sugar_mixed_juice { get; set; }
        public Nullable<decimal> non_sugar_mixed_juice_percent_cane { get; set; }
        public Nullable<decimal> pol_in_bagasse_qtl { get; set; }
        public Nullable<decimal> pol_in_bagasse_percentage_cane { get; set; }
        public Nullable<decimal> brix_in_bagasse_qtl { get; set; }
        public Nullable<decimal> brix_precent_bagasse { get; set; }
        public Nullable<decimal> brix_in_bagasse_precent_cane { get; set; }
        public Nullable<decimal> brix_in_cane { get; set; }
        public Nullable<decimal> brix_percent_cane { get; set; }
        public Nullable<decimal> pol_in_cane_qtl { get; set; }
        public Nullable<decimal> pol_in_cane_percent { get; set; }
        public Nullable<decimal> pol_in_press_cake_qtl { get; set; }
        public Nullable<decimal> pol_in_press_cake_percentage_cane { get; set; }
        public Nullable<decimal> brix_in_press_cake_qtl { get; set; }
        public Nullable<decimal> brix_in_press_cake_percentage_cane { get; set; }
        public Nullable<decimal> moist_bagasse_qtl { get; set; }
        public Nullable<decimal> moist_bagasse_in_percent_cane { get; set; }
        public Nullable<decimal> moist_percent_bagasse { get; set; }
        public Nullable<decimal> fiber_percent_bagasse { get; set; }
        public Nullable<decimal> fiber_in_bagasse_qtl { get; set; }
        public Nullable<decimal> fiber_percent_cane { get; set; }
        public Nullable<decimal> dry_mill_factor { get; set; }
        public Nullable<decimal> dry_mill_factor_percent_cane { get; set; }
        public Nullable<decimal> pol_in_clear_juice_qtl { get; set; }
        public Nullable<decimal> pol_in_clear_juice_percentage_cane { get; set; }
        public Nullable<decimal> brix_in_clear_juice_qtl { get; set; }
        public Nullable<decimal> brix_in_clear_juicce_percentage_cane { get; set; }
        public Nullable<decimal> non_sugar_in_clear_juice_qtl { get; set; }
        public Nullable<decimal> non_sugar_clear_juice_percentage_cane { get; set; }
        public Nullable<decimal> non_sugar_in_cj_percent_non_sugar_in_mj { get; set; }
        public Nullable<decimal> clear_juice_qtl { get; set; }
        public Nullable<decimal> clear_juice_qtl_percentage_cane { get; set; }
        public Nullable<decimal> non_sugar_final_molasses { get; set; }
        public Nullable<decimal> estimated_molasses_qtl { get; set; }
        public Nullable<decimal> estimated_molasses_percent_cane { get; set; }
        public Nullable<decimal> pol_in_molasses_qtl { get; set; }
        public Nullable<decimal> pol_in_molasses_percent_cane { get; set; }
        public Nullable<decimal> unknown_loss_qtl { get; set; }
        public Nullable<decimal> unknown_loss_percent_cane { get; set; }
        public Nullable<decimal> available_sugar_qtl { get; set; }
        public Nullable<decimal> available_sugar_qtl_percent_cane { get; set; }
        public Nullable<decimal> estimated_sugar_qtl { get; set; }
        public Nullable<decimal> estimated_sugar_percent_cane { get; set; }
        public Nullable<decimal> sugar_in_process_qtl { get; set; }
        public Nullable<decimal> sugar_in_process_percent_cane { get; set; }
        public Nullable<decimal> molasses_in_process_qtl { get; set; }
        public Nullable<decimal> molasses_in_process_percent_cane { get; set; }
        public Nullable<decimal> sugar_in_sugar { get; set; }
        public Nullable<decimal> sugar_in_sugar_percent_cane { get; set; }
        public Nullable<decimal> unknown_losses_calculated { get; set; }
        public Nullable<decimal> unknown_losses_calculated_percent_cane { get; set; }
        public Nullable<decimal> total_losses { get; set; }
        public Nullable<decimal> total_losses_percent { get; set; }
        public Nullable<decimal> java_ratio { get; set; }
        public Nullable<decimal> clerification_efficiency { get; set; }
        public Nullable<decimal> clerification_factor { get; set; }
        public Nullable<decimal> mill_extraction { get; set; }
        public Nullable<decimal> lost_juice_per_fiber { get; set; }
        public Nullable<decimal> reduced_mill_extraction_deer { get; set; }
        public Nullable<decimal> reduced_mill_extraction_mittal { get; set; }
        public Nullable<decimal> boiling_house_recovery { get; set; }
        public Nullable<decimal> bhr_basic { get; set; }
        public Nullable<decimal> virtual_purity_final_molasses { get; set; }
        public Nullable<decimal> reduced_boiling_house_recovery_deer { get; set; }
        public Nullable<decimal> reduced_boilin_house_recovery_rao { get; set; }
        public Nullable<decimal> over_all_recovery { get; set; }
        public Nullable<decimal> reduced_overall_recovery_deer { get; set; }
        public Nullable<decimal> reduced_overall_recovery_rao { get; set; }
        public Nullable<decimal> efficiency_percent_avail_sucros_in_mixed_juice { get; set; }
        public Nullable<decimal> efficiency_percent_avail_sucros_in_primary_juice { get; set; }
        public Nullable<decimal> erq_mj_to_pj { get; set; }
        public Nullable<decimal> erq_lj_to_pj { get; set; }
        public Nullable<decimal> extracted_mj_added_water { get; set; }
        public Nullable<decimal> brix_free_cane_water_percent_cane { get; set; }
        public Nullable<decimal> brix_free_cane_water_percent_fiber { get; set; }
        public Nullable<decimal> milling_ratio { get; set; }
        public Nullable<decimal> dilution_percent_pj_to_added_water { get; set; }
        public Nullable<decimal> added_water_percent_fiber { get; set; }
        public Nullable<decimal> undiluted_juice_extracted { get; set; }
        public Nullable<decimal> undiluted_juice_lost_percent_fiber { get; set; }
        public Nullable<decimal> dilution_percent_cane { get; set; }
        public Nullable<decimal> undiulted_juice_percent_cane { get; set; }
        public Nullable<decimal> total_juice { get; set; }
        public Nullable<decimal> combined_bagasse_average { get; set; }
        public Nullable<decimal> combined_bagasse_moist_percent { get; set; }
        public Nullable<decimal> press_cake_average { get; set; }
        public Nullable<decimal> sp_gravity { get; set; }
        public Nullable<decimal> combined_pj_brix { get; set; }
        public Nullable<decimal> combined_Pj_pol { get; set; }
        public Nullable<decimal> combined_pj_purity { get; set; }
        public Nullable<decimal> combined_pj_solids { get; set; }
        public Nullable<decimal> combined_pj_pol_qtl { get; set; }
        public Nullable<decimal> combined_lj_brix { get; set; }
        public Nullable<decimal> combined_lj_pol { get; set; }
        public Nullable<decimal> combined_lj_purity { get; set; }
        public Nullable<decimal> combined_mj_brix { get; set; }
        public Nullable<decimal> combined_mj_pol { get; set; }
        public Nullable<decimal> combined_mj_purity { get; set; }
        public Nullable<decimal> combined_mj_solids { get; set; }
        public Nullable<decimal> combined_mj_pol_qtl { get; set; }
        public Nullable<decimal> combined_pj_pol_avg { get; set; }
        public Nullable<decimal> combined_pj_brix_avg { get; set; }
        public Nullable<decimal> combined_lj_brix_avg { get; set; }
        public Nullable<decimal> combined_lj_pol_avg { get; set; }
        public Nullable<decimal> combined_lj_brix_solid { get; set; }
        public Nullable<decimal> combined_lj_pol_qtl { get; set; }
        public Nullable<decimal> clear_juice_brix { get; set; }
        public Nullable<decimal> clear_juice_pol { get; set; }
        public Nullable<decimal> clear_juice_purity { get; set; }
        public Nullable<decimal> oliver_brix { get; set; }
        public Nullable<decimal> oliver_pol { get; set; }
        public Nullable<decimal> oliver_purity { get; set; }
        public Nullable<decimal> brix_in_final_mol_qtl { get; set; }
        public Nullable<decimal> pol_in_final_mol_qtl { get; set; }
        public Nullable<decimal> non_sugar_in_final_mol_qtl { get; set; }
        public Nullable<decimal> non_sugar_in_final_mol_percent_cane { get; set; }
        public Nullable<decimal> final_molasses_sent_out { get; set; }
        public Nullable<decimal> final_molasses_sent_out_solids { get; set; }
        public Nullable<decimal> final_molasses_sent_out_pol_qtl { get; set; }
        public Nullable<decimal> final_molasses_brix { get; set; }
        public Nullable<decimal> final_molasses_pol { get; set; }
        public Nullable<decimal> final_molasses_purity { get; set; }
        public Nullable<decimal> unknown_loss { get; set; }
        public Nullable<decimal> boiling_house_extraction { get; set; }
        public Nullable<decimal> overall_extraction { get; set; }
        public Nullable<decimal> total_sugar_bagged { get; set; }
        public Nullable<decimal> remelting_sugar_totals { get; set; }
        public Nullable<decimal> remelting_raw_sugar_total { get; set; }
        public Nullable<decimal> net_sugar_bagged { get; set; }
        public Nullable<decimal> remelting_molasses_total { get; set; }
        public Nullable<decimal> remelting_raw_molasses_total { get; set; }
        public Nullable<decimal> net_molasses_sent_out { get; set; }
        public Nullable<decimal> combined_juice { get; set; }
        public Nullable<decimal> combined_mj_brix_qtl { get; set; }
        public Nullable<decimal> pj_brix_qtl { get; set; }
        public Nullable<decimal> pj_pol_qtl { get; set; }
        public Nullable<decimal> un_sulphered_brix { get; set; }
        public Nullable<decimal> un_sulphered_pol { get; set; }
        public Nullable<decimal> un_sulphered_purity { get; set; }
        public Nullable<decimal> sulphered_brix { get; set; }
        public Nullable<decimal> sulphered_pol { get; set; }
        public Nullable<decimal> sulphered_purity { get; set; }
        public Nullable<decimal> theoretical_final_molasses_qtl { get; set; }
        public Nullable<decimal> theoretical_final_molasses_percent_cane { get; set; }
        public Nullable<decimal> actual_percent_theoretical_final_molasses_percent_cane { get; set; }
        public Nullable<decimal> a_mass_pol { get; set; }
        public Nullable<decimal> a_mass_brix { get; set; }
        public Nullable<decimal> a_mass_purity { get; set; }
        public Nullable<decimal> a1_mass_pol { get; set; }
        public Nullable<decimal> a1_mass_brix { get; set; }
        public Nullable<decimal> a1_mass_purity { get; set; }
        public Nullable<decimal> b_mass_pol { get; set; }
        public Nullable<decimal> b_mass_brix { get; set; }
        public Nullable<decimal> b_mass_purity { get; set; }
        public Nullable<decimal> c1_mass_pol { get; set; }
        public Nullable<decimal> c1_mass_brix { get; set; }
        public Nullable<decimal> c1_mass_purity { get; set; }
        public Nullable<decimal> c_mass_pol { get; set; }
        public Nullable<decimal> c_mass_brix { get; set; }
        public Nullable<decimal> c_mass_purity { get; set; }
        public Nullable<decimal> raw_mass_pol { get; set; }
        public Nullable<decimal> raw_mass_brix { get; set; }
        public Nullable<decimal> raw_mass_purity { get; set; }
        public Nullable<decimal> r1_mass_pol { get; set; }
        public Nullable<decimal> r1_mass_brix { get; set; }
        public Nullable<decimal> r1_mass_purity { get; set; }
        public Nullable<decimal> r3_mass_pol { get; set; }
        public Nullable<decimal> r3_mass_brix { get; set; }
        public Nullable<decimal> r3_mass_purity { get; set; }
        public Nullable<decimal> cane_centre { get; set; }
        public Nullable<decimal> cane_gate { get; set; }
        public Nullable<decimal> bagasse_sold { get; set; }
        public Nullable<decimal> store_sulpher { get; set; }
        public Nullable<decimal> store_phosphoric { get; set; }
        public Nullable<decimal> store_lime { get; set; }
        public Nullable<decimal> store_viscosity_reducer { get; set; }
        public Nullable<decimal> store_biocide { get; set; }
        public Nullable<decimal> store_color_reducer { get; set; }
        public Nullable<decimal> store_magnafloe { get; set; }
        public Nullable<decimal> store_lub_oil { get; set; }
        public Nullable<decimal> store_lub_grease { get; set; }
        public Nullable<decimal> store_boiler_chemical { get; set; }
        public Nullable<decimal> store_sulpher_percent_cane { get; set; }
        public Nullable<decimal> store_phosphoric_percent_cane { get; set; }
        public Nullable<decimal> store_lime_percent_cane { get; set; }
        public Nullable<decimal> store_viscosity_reducer_percent_cane { get; set; }
        public Nullable<decimal> store_biocide_percent_cane { get; set; }
        public Nullable<decimal> store_color_reducer_percent_cane { get; set; }
        public Nullable<decimal> store_magnafloe_percent_cane { get; set; }
        public Nullable<decimal> store_lub_oil_percent_cane { get; set; }
        public Nullable<decimal> store_lub_grease_percent_cane { get; set; }
        public Nullable<decimal> store_boiler_chemical_percent_cane { get; set; }
        public Nullable<decimal> cane_early { get; set; }
        public Nullable<decimal> cane_general { get; set; }
        public Nullable<decimal> cane_reject { get; set; }
        public Nullable<decimal> cane_farm { get; set; }
        public Nullable<decimal> cane_early_percent { get; set; }
        public Nullable<decimal> cane_general_percent { get; set; }
        public Nullable<decimal> cane_reject_percent { get; set; }
        public Nullable<decimal> cane_gate_percent { get; set; }
        public Nullable<decimal> cane_centre_percent { get; set; }
        public Nullable<decimal> cane_farm_percent { get; set; }
        public Nullable<decimal> final_molasses_sent_out_percent { get; set; }

        public Nullable<decimal> cane_burnt { get; set; }
        public Nullable<decimal> cane_burnt_percent { get; set; }
        public Nullable<decimal> store_washing_soda { get; set; }
        public Nullable<decimal> store_hydrocloric_acid { get; set; }
        public Nullable<decimal> store_de_scaling_chemical { get; set; }
        public Nullable<decimal> store_seed_slurry { get; set; }
        public Nullable<decimal> store_anti_fomer { get; set; }
        public Nullable<decimal> store_chemical_for_brs_cleaning { get; set; }
        public Nullable<int> available_minutes { get; set; }
        public Nullable<decimal> EvaporationPercentClearJuice { get; set; }
        public Nullable<decimal> TotalNetClearJuice { get; set; }
        public Nullable<decimal> ClearJuiceDiversion { get; set; }
        public Nullable<decimal> DivertedCane { get; set; }
        public Nullable<decimal> DivertedMixedJuice { get; set; }
        public Nullable<decimal> loss_in_diverted_cane_qtl { get; set; }
    }
}