using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LitmusWeb.Models.ReportModel
{
    public class SummarizedReportModel
    {
        public Nullable<System.DateTime> report_date { get; set; }
        public string company_name { get; set; }
        public string unit_name { get; set; }
        public string unit_address { get; set; }
        public string season_year { get; set; }
        public Nullable<int> crop_day { get; set; }
        public Nullable<decimal> od_cane_crushed { get; set; }
        public Nullable<decimal> td_cane_crushed { get; set; }
        public Nullable<decimal> od_cane_early { get; set; }
        public Nullable<decimal> td_cane_early { get; set; }
        public Nullable<decimal> od_cane_early_percent { get; set; }
        public Nullable<decimal> td_cane_early_percent { get; set; }
        public Nullable<decimal> od_cane_general { get; set; }
        public Nullable<decimal> td_cane_general { get; set; }
        public Nullable<decimal> od_cane_general_percent { get; set; }
        public Nullable<decimal> td_cane_general_percent { get; set; }
        public Nullable<decimal> od_cane_reject { get; set; }
        public Nullable<decimal> td_cane_reject { get; set; }
        public Nullable<decimal> od_cane_reject_percent { get; set; }
        public Nullable<decimal> td_cane_reject_percent { get; set; }
        public Nullable<decimal> od_cane_burnt { get; set; }
        public Nullable<decimal> td_cane_burnt { get; set; }
        public Nullable<decimal> od_cane_burnt_percent { get; set; }
        public Nullable<decimal> td_cane_burnt_percent { get; set; }
        public Nullable<decimal> od_cane_farm { get; set; }
        public Nullable<decimal> td_cane_farm { get; set; }
        public Nullable<decimal> od_cane_farm_percent { get; set; }
        public Nullable<decimal> td_cane_farm_percent { get; set; }
        public Nullable<decimal> od_cane_centre { get; set; }
        public Nullable<decimal> td_cane_centre { get; set; }
        public Nullable<decimal> od_cane_centre_percent { get; set; }
        public Nullable<decimal> td_cane_centre_percent { get; set; }
        public Nullable<decimal> od_cane_gate { get; set; }
        public Nullable<decimal> td_cane_gate { get; set; }
        public Nullable<decimal> od_cane_gate_percent { get; set; }
        public Nullable<decimal> td_cane_gate_percent { get; set; }
        public Nullable<decimal> od_cane_gate_excluding_farm { get; set; }
        public Nullable<decimal> td_cane_gate_excluding_farm { get; set; }
        public Nullable<decimal> od_cane_gate_excluding_farm_percent { get; set; }
        public Nullable<decimal> td_cane_gate_excluding_farm_percent { get; set; }
        public Nullable<decimal> od_cane_gate_farm { get; set; }
        public Nullable<decimal> td_cane_gate_farm { get; set; }
        public Nullable<decimal> od_cane_gate_farm_percent_cane { get; set; }
        public Nullable<decimal> td_cane_gate_farm_percent_cane { get; set; }
        public Nullable<decimal> od_sugar_bagged { get; set; }
        public Nullable<decimal> td_sugar_bagged { get; set; }
        public Nullable<decimal> od_sugar_bagged_without_raw_sugar { get; set; }
        public Nullable<decimal> td_sugar_bagged_without_raw_sugar { get; set; }
        public Nullable<decimal> od_sugar_in_process { get; set; }
        public Nullable<decimal> td_sugar_in_process { get; set; }
        public Nullable<decimal> od_net_sugar_made { get; set; }
        public Nullable<decimal> td_net_sugar_made { get; set; }
        public Nullable<decimal> od_estimated_sugar_percent_cane { get; set; }
        public Nullable<decimal> td_estimated_sugar_percent_cane { get; set; }
        public Nullable<decimal> od_pol_in_cane_percent { get; set; }
        public Nullable<decimal> td_pol_in_cane_percent { get; set; }
        public Nullable<decimal> od_molasses_sentout_b_heavy { get; set; }
        public Nullable<decimal> od_molasses_sentout_c_heavy { get; set; }
        public Nullable<decimal> td_molasses_sentout_b_heavy { get; set; }
        public Nullable<decimal> td_molasses_sentout_c_heavy { get; set; }
        public Nullable<decimal> od_final_molasses_sent_out { get; set; }
        public Nullable<decimal> od_final_molasses_sent_out_percent_cane { get; set; }
        public Nullable<decimal> td_final_molasses_sentout { get; set; }
        public Nullable<decimal> td_final_molasses_sent_out_percent_cane { get; set; }
        public decimal od_trs_percent { get; set; }
        public Nullable<decimal> td_trs_percent { get; set; }
        public decimal od_rs_percent { get; set; }
        public Nullable<decimal> td_rs_percent { get; set; }
        public Nullable<decimal> od_molasses_in_process { get; set; }
        public Nullable<decimal> td_molasses_in_process { get; set; }
        public Nullable<decimal> od_net_molases_made_from_cane { get; set; }
        public Nullable<decimal> td_net_molasses_made_from_cane { get; set; }
        public Nullable<decimal> od_molasses_percent_cane { get; set; }
        public Nullable<decimal> td_molasses_perent_cane { get; set; }
        public Nullable<decimal> od_net_mixed_juice_percent_cane { get; set; }
        public Nullable<decimal> td_net_mixed_juice_percent_cane { get; set; }
        public Nullable<decimal> od_gross_mixed_juice_percent_cane { get; set; }
        public Nullable<decimal> td_gross_mixed_juice_percent_cane { get; set; }
        public Nullable<decimal> od_water_percent_cane { get; set; }
        public Nullable<decimal> td_water_percent_cane { get; set; }
        public decimal od_filter_water { get; set; }
        public Nullable<decimal> td_filter_water { get; set; }
        public Nullable<decimal> od_filter_water_percent_cane { get; set; }
        public Nullable<decimal> td_filter_water_percent_cane { get; set; }
        public Nullable<decimal> od_bagasse_percent_cane { get; set; }
        public Nullable<decimal> td_bagasse_percent_cane { get; set; }
        public Nullable<decimal> od_press_cake { get; set; }
        public Nullable<decimal> td_press_cake { get; set; }
        public Nullable<decimal> od_press_cake_percent_cane { get; set; }
        public Nullable<decimal> td_press_cake_percent_cane { get; set; }
        public Nullable<decimal> od_fiber_percent_cane { get; set; }
        public Nullable<decimal> td_fiber_percent_cane { get; set; }
        public Nullable<decimal> od_fiber_percent_bagasse { get; set; }
        public Nullable<decimal> td_fiber_percent_bagasse { get; set; }
        public Nullable<decimal> od_fiber_in_bagasse_qtl { get; set; }
        public Nullable<decimal> td_fiber_in_bagasse_qtl { get; set; }
        public Nullable<decimal> od_average_crush_including_stoppage { get; set; }
        public Nullable<decimal> td_average_crush_including_stoppage { get; set; }
        public Nullable<decimal> od_average_crushe_excluding_stoppage { get; set; }
        public Nullable<decimal> td_average_crushe_excluding_stoppage { get; set; }
        public short od_icumsa_l31 { get; set; }
        public Nullable<decimal> td_icumsa_l31 { get; set; }
        public short od_icumsa_M31 { get; set; }
        public Nullable<decimal> td_icumsa_m31 { get; set; }
        public short od_icumsa_S31 { get; set; }
        public Nullable<decimal> td_icumsa_s31 { get; set; }
        public short od_icumsa_l30 { get; set; }
        public Nullable<decimal> td_icumsa_l30 { get; set; }
        public short od_icumsa_M30 { get; set; }
        public Nullable<decimal> td_icumsa_m30 { get; set; }
        public short od_icumsa_S30 { get; set; }
        public Nullable<decimal> td_icumsa_s30 { get; set; }
        public Nullable<decimal> od_sugar_l31 { get; set; }
        public Nullable<decimal> td_sugar_l31 { get; set; }
        public Nullable<decimal> od_sugar_M31 { get; set; }
        public Nullable<decimal> td_sugar_M31 { get; set; }
        public Nullable<decimal> od_sugar_S31 { get; set; }
        public Nullable<decimal> td_sugar_S31 { get; set; }
        public Nullable<decimal> od_sugar_l30 { get; set; }
        public Nullable<decimal> td_sugar_l30 { get; set; }
        public Nullable<decimal> od_sugar_M30 { get; set; }
        public Nullable<decimal> td_sugar_M30 { get; set; }
        public Nullable<decimal> od_sugar_S30 { get; set; }
        public Nullable<decimal> td_sugar_S30 { get; set; }
        public Nullable<decimal> od_sugar_biss { get; set; }
        public Nullable<decimal> td_sugar_biss { get; set; }
        public int od_icumsa_raw { get; set; }
        public Nullable<decimal> od_raw_sugar { get; set; }
        public Nullable<decimal> td_raw_sugar { get; set; }
        public decimal od_iu_primary_juice { get; set; }
        public Nullable<decimal> td_iu_primary_juice { get; set; }
        public decimal od_iu_mixed_juice { get; set; }
        public Nullable<decimal> td_iu_mixed_juice { get; set; }
        public decimal od_iu_clear_juice { get; set; }
        public Nullable<decimal> td_iu_clear_juice { get; set; }
        public Nullable<decimal> od_l31_percent { get; set; }
        public Nullable<decimal> td_l31_percent { get; set; }
        public Nullable<decimal> od_M31_percent { get; set; }
        public Nullable<decimal> td_M31_percent { get; set; }
        public Nullable<decimal> od_S31_percent { get; set; }
        public Nullable<decimal> td_S31_percent { get; set; }
        public Nullable<decimal> od_l30_percent { get; set; }
        public Nullable<decimal> td_l30_percent { get; set; }
        public Nullable<decimal> od_M30_percent { get; set; }
        public Nullable<decimal> td_M30_percent { get; set; }
        public Nullable<decimal> od_S30_percent { get; set; }
        public Nullable<decimal> td_S30_percent { get; set; }
        public Nullable<decimal> od_raw_percent { get; set; }
        public Nullable<decimal> td_raw_percent { get; set; }
        public Nullable<decimal> od_biss_percent { get; set; }
        public Nullable<decimal> td_biss_percent { get; set; }
        public Nullable<decimal> od_primary_juice_brix { get; set; }
        public Nullable<decimal> od_primary_juice_pol { get; set; }
        public Nullable<decimal> od_primary_juice_purity { get; set; }
        public Nullable<decimal> td_primary_juice_brix { get; set; }
        public Nullable<decimal> td_primary_juice_pol { get; set; }
        public Nullable<decimal> td_primary_juice_purity { get; set; }
        public Nullable<decimal> od_mixed_juice_brix { get; set; }
        public Nullable<decimal> od_mixed_juice_pol { get; set; }
        public Nullable<decimal> od_mixed_juice_purity { get; set; }
        public Nullable<decimal> td_mixed_juice_brix { get; set; }
        public Nullable<decimal> td_mixed_juice_pol { get; set; }
        public Nullable<decimal> td_mixed_juice_purity { get; set; }
        public Nullable<decimal> od_last_mill_juice_brix { get; set; }
        public Nullable<decimal> od_last_mill_juice_pol { get; set; }
        public Nullable<decimal> od_last_mill_juice_purity { get; set; }
        public Nullable<decimal> td_last_mill_juice_brix { get; set; }
        public Nullable<decimal> td_last_mill_juice_pol { get; set; }
        public Nullable<decimal> td_last_mill_juice_purity { get; set; }
        public Nullable<decimal> od_clear_juice_brix { get; set; }
        public Nullable<decimal> od_clear_juice_pol { get; set; }
        public Nullable<decimal> od_clear_juice_purity { get; set; }
        public Nullable<decimal> td_clear_juice_brix { get; set; }
        public Nullable<decimal> td_clear_juice_pol { get; set; }
        public Nullable<decimal> td_clear_juice_purity { get; set; }
        public Nullable<decimal> od_oliver_brix { get; set; }
        public Nullable<decimal> od_oliver_pol { get; set; }
        public Nullable<decimal> od_oliver_purity { get; set; }
        public Nullable<decimal> td_oliver_brix { get; set; }
        public Nullable<decimal> td_oliver_pol { get; set; }
        public Nullable<decimal> td_oliver_purity { get; set; }
        public Nullable<decimal> od_unsulphured_syrup_brix { get; set; }
        public Nullable<decimal> od_unsulphured_syrup_pol { get; set; }
        public Nullable<decimal> od_unsulphured_syrup_purity { get; set; }
        public Nullable<decimal> td_unsulphured_syrup_brix { get; set; }
        public Nullable<decimal> td_unsulphured_syrup_pol { get; set; }
        public Nullable<decimal> td_unsulphured_syrup_purity { get; set; }
        public Nullable<decimal> od_sulphured_syrup_brix { get; set; }
        public Nullable<decimal> od_sulphured_syrup_pol { get; set; }
        public Nullable<decimal> od_sulphured_syrup_purity { get; set; }
        public Nullable<decimal> td_sulphured_syrup_brix { get; set; }
        public Nullable<decimal> td_sulphured_syrup_pol { get; set; }
        public Nullable<decimal> td_sulphured_syrup_purity { get; set; }
        public Nullable<decimal> od_final_molasses_brix { get; set; }
        public Nullable<decimal> od_final_molasses_pol { get; set; }
        public Nullable<decimal> od_final_molasses_purity { get; set; }
        public Nullable<decimal> td_final_molasses_brix { get; set; }
        public Nullable<decimal> td_final_molasses_pol { get; set; }
        public Nullable<decimal> td_final_molasses_purity { get; set; }
        public Nullable<decimal> od_primary_juice_ph { get; set; }
        public Nullable<decimal> od_mixed_juice_ph { get; set; }
        public Nullable<decimal> od_clear_juice_ph { get; set; }
        public Nullable<decimal> od_sulphered_ph { get; set; }
        public Nullable<decimal> od_unsulphered_ph { get; set; }
        public Nullable<decimal> od_combined_bagasse_pol { get; set; }
        public Nullable<decimal> td_combined_bagasse_pol { get; set; }
        public Nullable<decimal> od_combined_bagasse_moisture_percent { get; set; }
        public Nullable<decimal> td_combined_bagasse_moisture_percent { get; set; }
        public Nullable<decimal> od_dirt_correction_percent_cane { get; set; }
        public Nullable<decimal> td_dirt_correction_percent_cane { get; set; }
        public Nullable<decimal> od_press_cake_avg { get; set; }
        public Nullable<decimal> td_press_cake_avg { get; set; }
        public Nullable<decimal> od_press_cake_moisture_average { get; set; }
        public Nullable<decimal> od_virtual_purity_final_molasses { get; set; }
        public Nullable<decimal> od_extracted_mixed_juice_added_water { get; set; }
        public Nullable<decimal> td_extracted_mixed_juice_added_water { get; set; }
        public Nullable<decimal> od_lost_juice_per_fiber { get; set; }
        public Nullable<decimal> od_brix_free_cane_water_percent_cane { get; set; }
        public Nullable<decimal> od_milling_ratio { get; set; }
        public Nullable<decimal> od_undiluted_juice_extracted { get; set; }
        public Nullable<decimal> td_undiluted_juice_extracted { get; set; }
        public Nullable<decimal> od_undiluted_lost_percent_fiber { get; set; }
        public Nullable<decimal> td_undiluted_juice_lost_percent_fiber { get; set; }
        public Nullable<decimal> od_dilution_percent_cane { get; set; }
        public Nullable<decimal> od_undiluted_juice_percent_cane { get; set; }
        public Nullable<decimal> td_undiluted_juice_percent_cane { get; set; }
        public Nullable<decimal> od_added_water_percent_fiber { get; set; }
        public Nullable<decimal> td_added_water_percent_fiber { get; set; }
        public Nullable<decimal> od_dilution_percent_primary_juice_to_added_water { get; set; }
        public Nullable<decimal> od_brix_percent_cane { get; set; }
        public Nullable<decimal> td_brix_percent_cane { get; set; }
        public Nullable<decimal> od_pol_in_mixed_juice_percent { get; set; }
        public Nullable<decimal> od_pol_in_bagasse_percent { get; set; }
        public Nullable<decimal> td_pol_in_bagasse_percent { get; set; }
        public Nullable<decimal> od_pol_in_press_cake { get; set; }
        public Nullable<decimal> td_pol_in_percent_cane { get; set; }
        public Nullable<decimal> od_pol_in_molasses_percent_cane { get; set; }
        public Nullable<decimal> td_pol_in_molasses_percent_cane { get; set; }
        public Nullable<decimal> od_unknown_loss { get; set; }
        public Nullable<decimal> td_unknown_loss { get; set; }
        public Nullable<decimal> od_total_loss { get; set; }
        public Nullable<decimal> td_total_loss { get; set; }
        public Nullable<decimal> od_sugar_in_sugar_percent { get; set; }
        public Nullable<decimal> td_sugar_in_sugar_percent { get; set; }
        public Nullable<decimal> od_dmf { get; set; }
        public Nullable<decimal> td_dmf { get; set; }
        public Nullable<decimal> od_java_ratio { get; set; }
        public Nullable<decimal> td_java_ratio { get; set; }
        public Nullable<decimal> od_clerification_efficiency { get; set; }
        public Nullable<decimal> td_clerification_efficiency { get; set; }
        public Nullable<decimal> od_mill_extraction { get; set; }
        public Nullable<decimal> td_mill_extraction { get; set; }
        public Nullable<decimal> od_boiling_house_recovery { get; set; }
        public Nullable<decimal> td_boiling_house_recovery { get; set; }
        public Nullable<decimal> od_reduced_mill_extraction_deer { get; set; }
        public Nullable<decimal> td_reduced_mill_extraction_deer { get; set; }
        public Nullable<decimal> od_bhr_basic { get; set; }
        public Nullable<decimal> td_bhr_basic { get; set; }
        public Nullable<decimal> od_reduced_boiling_house_recovery_deer { get; set; }
        public Nullable<decimal> td_reduced_boiling_house_recovery_deer { get; set; }
        public Nullable<decimal> od_reduced_overall_recovery_deer { get; set; }
        public Nullable<decimal> td_reduced_overall_recovery_deer { get; set; }
        public Nullable<decimal> od_erq_mj_to_pj { get; set; }
        public Nullable<decimal> td_erq_mj_to_pj { get; set; }
        public Nullable<decimal> od_erq_lj_to_pj { get; set; }
        public Nullable<decimal> td_erq_lj_to_pj { get; set; }
        public decimal od_nm_p_index { get; set; }
        public Nullable<decimal> td_p_index { get; set; }
        public decimal od_nm_pry_ext { get; set; }
        public Nullable<decimal> td_pry_ext { get; set; }
        public Nullable<decimal> od_cane_purchased { get; set; }
        public Nullable<decimal> td_cane_purchased { get; set; }
        public Nullable<decimal> od_cane_balance { get; set; }
        public Nullable<decimal> td_cane_balance { get; set; }
        public decimal od_temp_min { get; set; }
        public Nullable<decimal> td_temp_min { get; set; }
        public decimal od_temp_max { get; set; }
        public Nullable<decimal> td_temp_max { get; set; }
        public decimal od_humidity { get; set; }
        public decimal od_rain_fall { get; set; }
        public Nullable<decimal> td_rain_fall { get; set; }
        public decimal od_live_steam_generation { get; set; }
        public Nullable<decimal> td_live_steam_generation { get; set; }
        public decimal od_live_steam_consumption { get; set; }
        public Nullable<decimal> td_live_steam_consumption { get; set; }
        public decimal od_power_turnines { get; set; }
        public Nullable<decimal> td_power_turbines { get; set; }
        public Nullable<decimal> od_live_steam_generation_ton { get; set; }
        public Nullable<decimal> td_live_steam_generation_ton { get; set; }
        public Nullable<decimal> td_live_steam_consumption_ton { get; set; }
        public Nullable<decimal> od_power_turnines_ton { get; set; }
        public Nullable<decimal> td_power_turbines_ton { get; set; }
        public decimal od_bleeding_acf { get; set; }
        public Nullable<decimal> td_bleeding_acf { get; set; }
        public decimal od_d_super_heating { get; set; }
        public Nullable<decimal> td_d_super_heating { get; set; }
        public Nullable<decimal> od_drain_pipe_loss { get; set; }
        public Nullable<decimal> td_drain_pipe_loss { get; set; }
        public decimal od_exhaust_steam_generation { get; set; }
        public Nullable<decimal> td_exhaust_steam_generation { get; set; }
        public Nullable<decimal> od_exhaust_steam_generation_ton { get; set; }
        public Nullable<decimal> td_exhaust_steam_generation_ton { get; set; }
        public Nullable<decimal> od_steam_percent_cane { get; set; }
        public Nullable<decimal> td_steam_percent_cane { get; set; }
        public decimal od_steam_per_ten_ton_sugar { get; set; }
        public Nullable<decimal> td_steam_per_ten_ton_sugar { get; set; }
        public decimal od_power_per_hundred_ton_sugar { get; set; }
        public Nullable<decimal> td_power_per_hundred_ton_sugar { get; set; }
        public decimal od_power_per_ten_ton_sugar { get; set; }
        public Nullable<decimal> td_power_per_ten_ton_sugar { get; set; }
        public decimal od_power_from_grid { get; set; }
        public Nullable<decimal> td_power_from_grid { get; set; }
        public Nullable<decimal> od_power_from_grid_per_ton_cane { get; set; }
        public Nullable<decimal> td_power_from_grid_per_ton_cane { get; set; }
        public decimal od_power_import_cogen { get; set; }
        public Nullable<decimal> td_power_import_cogen { get; set; }
        public Nullable<decimal> od_power_import_cogen_per_ton_cane { get; set; }
        public Nullable<decimal> td_power_import_cogen_per_ton_cane { get; set; }
        public decimal od_power_from_sugar { get; set; }
        public Nullable<decimal> td_power_from_sugar { get; set; }
        public Nullable<decimal> od_power_from_sugar_per_ton_cane { get; set; }
        public Nullable<decimal> td_power_from_sugar_per_ton_cane { get; set; }
        public Nullable<decimal> od_total_power_consumed { get; set; }
        public Nullable<decimal> od_total_power_consumed_per_ton_cane { get; set; }
        public Nullable<decimal> td_total_power_consumed { get; set; }
        public Nullable<decimal> td_total_power_consumed_per_ton_cane { get; set; }
        public decimal od_total_power_per_qtl_sugar { get; set; }
        public Nullable<decimal> td_total_power_per_qtl_sugar { get; set; }
        public Nullable<decimal> td_total_power_per_ton_sugar { get; set; }
        public decimal od_power_generation_cogen { get; set; }
        public Nullable<decimal> od_power_generation_cogen_per_ton_cane { get; set; }
        public Nullable<decimal> td_power_generation_cogen { get; set; }
        public Nullable<decimal> td_power_generation_cogen_per_ton_cane { get; set; }
        public decimal od_power_export_from_cogen { get; set; }
        public Nullable<decimal> od_power_export_from_cogen_per_ton_cane { get; set; }
        public Nullable<decimal> td_power_export_from_cogen { get; set; }
        public decimal od_power_dg_set { get; set; }
        public Nullable<decimal> td_power_dg_set { get; set; }
        public Nullable<decimal> td_power_export_from_cogen_per_ton_cane { get; set; }
        public Nullable<decimal> od_total_bagasse { get; set; }
        public Nullable<decimal> od_total_bagasse_percent_cane { get; set; }
        public Nullable<decimal> td_total_bagasse { get; set; }
        public Nullable<decimal> td_total_bagasse_percent_cane { get; set; }
        public Nullable<decimal> od_bagasse_consumed { get; set; }
        public Nullable<decimal> od_bagasse_consumed_percent_cane { get; set; }
        public Nullable<decimal> td_bagasse_consumed { get; set; }
        public Nullable<decimal> td_bagasse_consumed_percent_cane { get; set; }
        public Nullable<decimal> od_bagasse_sold { get; set; }
        public Nullable<decimal> od_bagasse_sold_percent_cane { get; set; }
        public Nullable<decimal> td_bagasse_sold { get; set; }
        public Nullable<decimal> td_bagasse_sold_percent_cane { get; set; }
        public Nullable<decimal> od_bagasse_saved { get; set; }
        public Nullable<decimal> td_bagasse_saved { get; set; }
        public Nullable<decimal> od_nm_bagasse_pol_avg { get; set; }
        public Nullable<decimal> od_om_bagasse_pol_avg { get; set; }
        public decimal od_etp_ph { get; set; }
        public Nullable<decimal> td_etp_ph { get; set; }
        public decimal od_etp_tss { get; set; }
        public Nullable<decimal> td_etp_tss { get; set; }
        public decimal od_etp_cod { get; set; }
        public Nullable<decimal> td_etp_code { get; set; }
        public decimal od_etp_bod { get; set; }
        public Nullable<decimal> td_etp_bode { get; set; }
        public decimal od_etp_water_flow { get; set; }
        public Nullable<decimal> td_etp_water_flow { get; set; }
        public Nullable<long> od_total_operating_tube_well { get; set; }
        public Nullable<long> td_total_operating_tube_well { get; set; }
        public Nullable<decimal> od_exhaust_condensate_recovery { get; set; }
        public Nullable<decimal> td_exhaust_condensate_recovery { get; set; }
        public Nullable<decimal> od_T_c_massecuite_pan { get; set; }
        public Nullable<decimal> td_T_c_massecuite_pan { get; set; }
        public Nullable<decimal> od_water_pan_a { get; set; }
        public Nullable<decimal> od_water_pan_b { get; set; }
        public Nullable<decimal> od_pan_water_c { get; set; }
        public Nullable<decimal> od_water_percent_cane_pan_a { get; set; }
        public Nullable<decimal> od_water_percent_cane_pan_b { get; set; }
        public Nullable<decimal> od_water_percent_cane_pan_c { get; set; }
        public Nullable<decimal> od_pan_water_percent_cane { get; set; }
        public decimal od_pan_water_total { get; set; }
        public Nullable<decimal> td_water_pan_a { get; set; }
        public Nullable<decimal> td_water_pan_b { get; set; }
        public Nullable<decimal> td_water_pan_c { get; set; }
        public Nullable<decimal> td_water_consumption_percent_cane_pan_a { get; set; }
        public Nullable<decimal> td_water_consumption_percent_cane_pan_b { get; set; }
        public Nullable<decimal> td_water_consumption_percent_cane_pan_c { get; set; }
        public Nullable<decimal> td_pan_water_percent_cane { get; set; }
        public Nullable<decimal> td_pan_water_total { get; set; }
        public Nullable<decimal> total_pan_water_ton { get; set; }
        public Nullable<decimal> od_bleeding_acf_in_ton { get; set; }
        public Nullable<decimal> od_ata3_cogen_in_ton { get; set; }
        public decimal od_exhaust_steam_consumption { get; set; }
        public Nullable<decimal> td_exhaust_steam_consumption { get; set; }
        public Nullable<decimal> od_exhaust_steam_consumption_ton { get; set; }
        public Nullable<decimal> td_exhaust_steam_consumption_on { get; set; }
        public decimal od_steam_per_ton_cane_percent { get; set; }
        public Nullable<decimal> td_steam_per_ton_cane_percent { get; set; }
        public Nullable<int> od_balance_truck_count { get; set; }
        public Nullable<decimal> od_balance_truck_weight { get; set; }
        public Nullable<int> od_balance_trolley_count { get; set; }
        public Nullable<decimal> od_balance_trolley_weight { get; set; }
        public Nullable<int> od_balance_trippler_count { get; set; }
        public Nullable<decimal> od_balance_trippler_weight { get; set; }
        public Nullable<int> od_balance_cart_count { get; set; }
        public Nullable<decimal> od_balance_cart_weight { get; set; }
        public Nullable<decimal> od_a_massecuite_brix { get; set; }
        public Nullable<decimal> td_a_massecuite_brix { get; set; }
        public Nullable<decimal> od_a_massecuite_pol { get; set; }
        public Nullable<decimal> td_a_massecuite_a_pol { get; set; }
        public Nullable<decimal> od_a_massecuite_a_purity { get; set; }
        public Nullable<decimal> td_a_massecuite_purity { get; set; }
        public Nullable<decimal> od_a_massecuite_hl { get; set; }
        public Nullable<decimal> td_a_massecuite_hl { get; set; }
        public Nullable<decimal> od_a_massecuite_exhaustion { get; set; }
        public Nullable<decimal> td_a_massecuite_exhaustion { get; set; }
        public Nullable<decimal> od_a1_massecuite_brix { get; set; }
        public Nullable<decimal> td_a1_massecuite_brix { get; set; }
        public Nullable<decimal> od_a1_massecuite_pol { get; set; }
        public Nullable<decimal> td_a1_massecuite_a_pol { get; set; }
        public Nullable<decimal> od_a1_massecuite_a_purity { get; set; }
        public Nullable<decimal> td_a1_massecuite_purity { get; set; }
        public Nullable<decimal> od_a1_massecuite_hl { get; set; }
        public Nullable<decimal> td_a1_massecuite_hl { get; set; }
        public Nullable<decimal> od_b_massecuite_brix { get; set; }
        public Nullable<decimal> td_b_massecuite_brix { get; set; }
        public Nullable<decimal> od_b_massecuite_pol { get; set; }
        public Nullable<decimal> td_b_massecuite_b_pol { get; set; }
        public Nullable<decimal> od_b_massecuite_b_purity { get; set; }
        public Nullable<decimal> td_b_massecuite_purity { get; set; }
        public Nullable<decimal> od_b_massecuite_hl { get; set; }
        public Nullable<decimal> td_b_massecuite_hl { get; set; }
        public Nullable<decimal> od_b_massecuite_exhaustion { get; set; }
        public Nullable<decimal> td_b_massecuite_exhaustion { get; set; }
        public decimal od_c_massecuite_brix { get; set; }
        public decimal td_c_massecuite_brix { get; set; }
        public decimal od_c_massecuite_pol { get; set; }
        public decimal td_c_massecuite_c_pol { get; set; }
        public decimal od_c_massecuite_c_purity { get; set; }
        public decimal td_c_massecuite_purity { get; set; }
        public decimal od_c_massecuite_hl { get; set; }
        public decimal td_c_massecuite_hl { get; set; }
        public Nullable<decimal> od_c_massecuite_exhaustion { get; set; }
        public Nullable<decimal> td_c_massecuite_exhaustion { get; set; }
        public Nullable<decimal> od_c1_massecuite_brix { get; set; }
        public Nullable<decimal> td_c1_massecuite_brix { get; set; }
        public Nullable<decimal> od_c1_massecuite_pol { get; set; }
        public Nullable<decimal> td_c1_massecuite_c1_pol { get; set; }
        public Nullable<decimal> od_c1_massecuite_c1_purity { get; set; }
        public Nullable<decimal> td_c1_massecuite_purity { get; set; }
        public decimal od_c1_massecuite_hl { get; set; }
        public decimal td_c1_massecuite_hl { get; set; }
        public Nullable<decimal> od_a_heavy_brix { get; set; }
        public Nullable<decimal> td_a_heavy_brix { get; set; }
        public Nullable<decimal> od_a_heavy_pol { get; set; }
        public Nullable<decimal> td_a_heavy_pol { get; set; }
        public Nullable<decimal> od_a_heavy_purity { get; set; }
        public Nullable<decimal> td_a_heavy_purity { get; set; }
        public Nullable<decimal> od_a1_heavy_brix { get; set; }
        public Nullable<decimal> td_a1_heavy_brix { get; set; }
        public Nullable<decimal> od_a1_heavy_pol { get; set; }
        public Nullable<decimal> td_a1_heavy_pol { get; set; }
        public Nullable<decimal> od_a1_heavy_purity { get; set; }
        public Nullable<decimal> td_a1_heavy_purity { get; set; }
        public Nullable<decimal> od_b_heavy_brix { get; set; }
        public Nullable<decimal> td_b_heavy_brix { get; set; }
        public Nullable<decimal> od_b_heavy_pol { get; set; }
        public Nullable<decimal> td_b_heavy_pol { get; set; }
        public Nullable<decimal> od_b_heavy_purity { get; set; }
        public Nullable<decimal> td_b_heavy_purity { get; set; }
        public Nullable<decimal> od_c1_heavy_brix { get; set; }
        public Nullable<decimal> td_c1_heavy_brix { get; set; }
        public Nullable<decimal> od_c1_heavy_pol { get; set; }
        public Nullable<decimal> td_c1_heavy_pol { get; set; }
        public decimal od_c1_heavy_purity { get; set; }
        public decimal td_c1_heavy_purity { get; set; }
        public Nullable<decimal> od_a_light_brix { get; set; }
        public Nullable<decimal> td_a_light_brix { get; set; }
        public Nullable<decimal> od_a_light_pol { get; set; }
        public Nullable<decimal> td_a_light_pol { get; set; }
        public Nullable<decimal> od_a_light_purity { get; set; }
        public Nullable<decimal> td_a_light_purity { get; set; }
        public Nullable<decimal> od_c_light_brix { get; set; }
        public Nullable<decimal> td_c_light_brix { get; set; }
        public Nullable<decimal> od_c_light_pol { get; set; }
        public Nullable<decimal> td_c_light_pol { get; set; }
        public Nullable<decimal> od_c_light_purity { get; set; }
        public Nullable<decimal> td_c_light_purity { get; set; }
        public Nullable<decimal> od_dry_seed_brix { get; set; }
        public Nullable<decimal> td_dry_seed_brix { get; set; }
        public Nullable<decimal> od_dry_seed_pol { get; set; }
        public Nullable<decimal> td_dry_seed_pol { get; set; }
        public Nullable<decimal> od_dry_seed_purity { get; set; }
        public Nullable<decimal> td_dry_seed_purity { get; set; }
        public Nullable<decimal> od_melt_brix { get; set; }
        public Nullable<decimal> td_melt_brix { get; set; }
        public Nullable<decimal> od_melt_pol { get; set; }
        public Nullable<decimal> td_melt_pol { get; set; }
        public Nullable<decimal> od_melt_purity { get; set; }
        public Nullable<decimal> td_melt_purity { get; set; }
        public Nullable<decimal> od_c_single_brix { get; set; }
        public Nullable<decimal> td_c_single_brix { get; set; }
        public Nullable<decimal> od_c_single_pol { get; set; }
        public Nullable<decimal> td_c_single_pol { get; set; }
        public Nullable<decimal> od_c_single_purity { get; set; }
        public Nullable<decimal> td_c_single_purity { get; set; }
        public Nullable<decimal> od_c_double_brix { get; set; }
        public Nullable<decimal> td_c_double_brix { get; set; }
        public Nullable<decimal> od_c_double_pol { get; set; }
        public Nullable<decimal> td_c_double_pol { get; set; }
        public Nullable<decimal> od_c_double_purity { get; set; }
        public Nullable<decimal> td_c_double_purity { get; set; }
        public Nullable<decimal> od_b_sugar_brix { get; set; }
        public Nullable<decimal> td_b_sugar_brix { get; set; }
        public Nullable<decimal> od_b_sugar_pol { get; set; }
        public Nullable<decimal> td_b_sugar_pol { get; set; }
        public Nullable<decimal> od_b_sugar_purity { get; set; }
        public Nullable<decimal> td_b_sugar_purity { get; set; }
        public Nullable<decimal> od_remelting_molasses { get; set; }
        public Nullable<decimal> td_remelting_molasses { get; set; }
        public Nullable<decimal> od_remelting_sugar { get; set; }
        public Nullable<decimal> td_remelting_sugar { get; set; }
        public Nullable<decimal> od_gross_remelting { get; set; }
        public Nullable<decimal> td_gross_remelting { get; set; }
        public Nullable<decimal> od_store_sulphur { get; set; }
        public Nullable<decimal> td_store_sulphur { get; set; }
        public Nullable<decimal> od_store_sulpher_percent_cane { get; set; }
        public Nullable<decimal> td_store_sulpher_percent_cane { get; set; }
        public Nullable<decimal> od_store_lime { get; set; }
        public Nullable<decimal> td_store_lime { get; set; }
        public Nullable<decimal> od_store_lime_percent_cane { get; set; }
        public Nullable<decimal> td_store_lime_percent_cane { get; set; }
        public Nullable<decimal> od_store_phosphoric { get; set; }
        public Nullable<decimal> td_store_phosphoric { get; set; }
        public Nullable<decimal> od_store_phosphoric_percent_cane { get; set; }
        public Nullable<decimal> td_store_phosphoric_percent_cane { get; set; }
        public Nullable<decimal> od_store_viscosity_reducer { get; set; }
        public Nullable<decimal> td_store_viscosity_reducer { get; set; }
        public Nullable<decimal> od_store_viscosity_reducer_percent_cane { get; set; }
        public Nullable<decimal> td_store_viscosity_reducer_percent_cane { get; set; }
        public Nullable<decimal> od_store_biocide { get; set; }
        public Nullable<decimal> td_store_biocide { get; set; }
        public Nullable<decimal> od_store_biocide_percent_cane { get; set; }
        public Nullable<decimal> td_store_biocide_percent_cane { get; set; }
        public Nullable<decimal> od_store_color_reducer { get; set; }
        public Nullable<decimal> td_store_color_reducer { get; set; }
        public Nullable<decimal> od_store_color_reducer_percent_cane { get; set; }
        public Nullable<decimal> td_store_color_reducer_percent_cane { get; set; }
        public Nullable<decimal> od_store_magnafloe { get; set; }
        public Nullable<decimal> td_store_magnafloe { get; set; }
        public Nullable<decimal> od_store_magnafloe_percent_cane { get; set; }
        public Nullable<decimal> td_store_magnafloe_percent_cane { get; set; }
        public Nullable<decimal> od_store_lub_grease { get; set; }
        public Nullable<decimal> td_store_lub_grease { get; set; }
        public Nullable<decimal> od_store_lub_grease_percent_cane { get; set; }
        public Nullable<decimal> td_store_lub_grease_percent_cane { get; set; }
        public Nullable<decimal> od_store_lub_oil { get; set; }
        public Nullable<decimal> td_store_lub_oil { get; set; }
        public Nullable<decimal> od_store_lub_oil_percent_cane { get; set; }
        public Nullable<decimal> td_store_lub_oil_percent_cane { get; set; }
        public Nullable<decimal> od_store_boiler_chemical { get; set; }
        public Nullable<decimal> td_store_boiler_chemical { get; set; }
        public Nullable<decimal> od_store_boiler_chemical_percent_cane { get; set; }
        public Nullable<decimal> td_store_boiler_chemical_percent_cane { get; set; }
        public decimal od_store_washing_soda { get; set; }
        public decimal od_store_hydrolic_acid { get; set; }
        public decimal od_store_de_scaling_chemical { get; set; }
        public decimal od_store_seed_slurry { get; set; }
        public decimal od_store_anty_fomer { get; set; }
        public decimal od_store_chemical_for_brs_cleaning { get; set; }
        public Nullable<decimal> od_store_oil_greace_spgravity { get; set; }
        public Nullable<decimal> od_store_oil_greace_spgravity_percent_cane { get; set; }
        public Nullable<decimal> td_store_oil_greace_spgravity { get; set; }
        public Nullable<decimal> td_store_oil_greace_spgravity_percent_cane { get; set; }
        public short od_foreign_matter_L31 { get; set; }
        public Nullable<decimal> td_foreign_matter_L31 { get; set; }
        public short od_foreign_matter_M31 { get; set; }
        public Nullable<decimal> td_foreign_matter_M31 { get; set; }
        public short od_foreign_matter_S31 { get; set; }
        public Nullable<decimal> td_foreign_matter_S31 { get; set; }
        public short od_retention_L31 { get; set; }
        public Nullable<decimal> td_retention_L31 { get; set; }
        public short od_retention_M31 { get; set; }
        public Nullable<decimal> td_retention_M31 { get; set; }
        public short od_retention_S31 { get; set; }
        public Nullable<decimal> td_retention_S31 { get; set; }
        public decimal od_phosphate_mixed_juice { get; set; }
        public Nullable<decimal> td_phosphate_mixed_juice { get; set; }
        public decimal od_phosphate_clear_juice { get; set; }
        public Nullable<decimal> td_phosphate_clear_juice { get; set; }
        public decimal od_calcium_mixed_juice { get; set; }
        public Nullable<decimal> td_calcium_mixed_juice { get; set; }
        public decimal od_calcium_clear_juice { get; set; }
        public Nullable<decimal> td_calcium_clear_juice { get; set; }
        public string od_nm_cane { get; set; }
        public string od_om_cane { get; set; }
        public string od_combine_cane { get; set; }
        public string od_nm_engg { get; set; }
        public string od_om_engg { get; set; }
        public string od_combine_engg { get; set; }
        public string od_nm_cogen { get; set; }
        public string od_om_cogen { get; set; }
        public string od_combine_cogen { get; set; }
        public string od_nm_gen_cleaning { get; set; }
        public string od_om_gen_cleaning { get; set; }
        public string od_combine_gen_cleaning { get; set; }
        public string od_nm_fest { get; set; }
        public string od_om_fest { get; set; }
        public string od_combine_fest { get; set; }
        public string od_nm_weather { get; set; }
        public string od_om_weather { get; set; }
        public string od_combine_weather { get; set; }
        public string od_nm_process { get; set; }
        public string od_om_process { get; set; }
        public string od_combine_process { get; set; }
        public string od_nm_misc { get; set; }
        public string od_om_misc { get; set; }
        public string od_combine_misc { get; set; }
        public string od_nm_poor_feeding { get; set; }
        public string od_om_poor_feeding { get; set; }
        public string od_combine_poor_feeding { get; set; }
        public string od_total_nm_stoppage { get; set; }
        public string od_total_om_stoppage { get; set; }
        public string od_total_working_net_duration { get; set; }
        public string od_total_stoppages { get; set; }
        public string od_total_available_hours { get; set; }
        public Nullable<decimal> od_total_lost_time_percent { get; set; }
        public string od_om_gross_working_duration { get; set; }
        public string od_nm_gross_working_duration { get; set; }
        public string od_om_gross_stoppage_duration { get; set; }
        public string od_nm_gross_stoppage_duration { get; set; }
        public string od_total_gross_stoppage_duration { get; set; }
        public string td_nm_cane { get; set; }
        public string td_om_cane { get; set; }
        public string td_combine_cane { get; set; }
        public string td_nm_engg { get; set; }
        public string td_om_engg { get; set; }
        public string td_combine_engg { get; set; }
        public string td_nm_cogen { get; set; }
        public string td_om_cogen { get; set; }
        public string td_combine_cogen { get; set; }
        public string td_nm_gen_cleaning { get; set; }
        public string td_om_gen_cleaning { get; set; }
        public string td_combine_gen_cleaning { get; set; }
        public string td_nm_fest { get; set; }
        public string td_om_fest { get; set; }
        public string td_combine_fest { get; set; }
        public string td_nm_weather { get; set; }
        public string td_om_weather { get; set; }
        public string td_combine_weather { get; set; }
        public string td_nm_process { get; set; }
        public string td_om_process { get; set; }
        public string td_combine_process { get; set; }
        public string td_nm_misc { get; set; }
        public string td_om_misc { get; set; }
        public string td_combine_misc { get; set; }
        public string td_nm_poor_feeding { get; set; }
        public string td_om_poor_feeding { get; set; }
        public string td_combine_poor_feeding { get; set; }
        public string td_total_nm_stoppage { get; set; }
        public string td_total_om_stoppage { get; set; }
        public string td_total_stoppages { get; set; }
        public string td_total_working_hours { get; set; }
        public string td_total_available_hours { get; set; }
        public Nullable<decimal> td_total_lost_time_percent { get; set; }
        public string td_om_gross_working_duration { get; set; }
        public string td_nm_gross_working_duration { get; set; }
        public string td_om_gross_stoppage_duration { get; set; }
        public string td_nm_gross_stoppage_duration { get; set; }
        public string td_total_gross_stoppage_duration { get; set; }
        public Nullable<decimal> od_live_steam_consumption_ton { get; set; }
        public Nullable<decimal> td_steam_consumption_ton { get; set; }
        public Nullable<decimal> od_live_steam_consumption_ton_per_hour { get; set; }
        public Nullable<decimal> td_live_steam_consumption_ton_per_hour { get; set; }
        public Nullable<decimal> od_steam_consumption_percent_cane { get; set; }
        public Nullable<decimal> td_steam_consumption_percent_cane { get; set; }
        public Nullable<decimal> od_steam_consumption_without_d_super_heating { get; set; }
        public Nullable<decimal> td_steam_consumption_without_d_super_heating { get; set; }
        public Nullable<decimal> od_steam_consumption_without_d_superheating_percent_cane { get; set; }
        public Nullable<decimal> td_steam_consumption_without_d_superheating_percent_cane { get; set; }
        public Nullable<decimal> od_d_superheating_ton { get; set; }
        public Nullable<decimal> td_d_superheating_ton { get; set; }
        public Nullable<decimal> od_d_super_heating_ton_per_hour { get; set; }
        public Nullable<decimal> td_d_super_heating_ton_per_hour { get; set; }
        public Nullable<decimal> od_d_super_heating_percent_cane { get; set; }
        public Nullable<decimal> td_d_super_heating_percent_cane { get; set; }
        public Nullable<decimal> od_steam_from_cogen_ton { get; set; }
        public Nullable<decimal> td_steam_from_cogen_ton { get; set; }
        public Nullable<decimal> od_steam_from_cogen_ton_per_hour { get; set; }
        public Nullable<decimal> td_steam_from_cogen_ton_per_hour { get; set; }
        public Nullable<decimal> od_steam_from_cogen_percent_cane { get; set; }
        public Nullable<decimal> td_steam_from_cogen_percent_cane { get; set; }
        public string day_hours { get; set; }
        public System.DateTime crushing_start_date { get; set; }
        public string crushing_start_time { get; set; }
        public Nullable<decimal> od_overtime_engg_replacement { get; set; }
        public Nullable<decimal> td_overtime_engg_replacement { get; set; }
        public Nullable<decimal> od_overtime_eng_extra { get; set; }
        public Nullable<decimal> td_overtime_eng_extra { get; set; }
        public Nullable<decimal> od_overtime_mfg_replacement { get; set; }
        public Nullable<decimal> td_overtime_mfg_replacement { get; set; }
        public Nullable<decimal> od_overtime_mfg_extra { get; set; }
        public Nullable<decimal> td_overtime_mfg_extra { get; set; }
        public Nullable<decimal> od_StoreProcessChemicalQuantity { get; set; }
        public Nullable<decimal> td_StoreProcessChemicalQuantity { get; set; }
        public Nullable<decimal> od_StoreProcessChemicalAmount { get; set; }
        public Nullable<decimal> td_StoreProcessChemicalAmount { get; set; }
        public Nullable<decimal> od_StoreProcessChemicalPerBagRate { get; set; }
        public Nullable<decimal> td_StoreProcessChemicalPerBagRate { get; set; }
        public Nullable<decimal> od_StoreProcessChemicalPerTonCaneRate { get; set; }
        public Nullable<decimal> td_StoreProcessChemicalPerTonCaneRate { get; set; }
        public Nullable<decimal> od_StoreBoilerChemicalQuantity { get; set; }
        public Nullable<decimal> td_StoreBoilerChemicalQuantity { get; set; }
        public Nullable<decimal> od_StoreBoilerChemicalAmount { get; set; }
        public Nullable<decimal> td_StoreBoilerChemicalAmount { get; set; }
        public Nullable<decimal> od_StoreBoilerChemicalPerBagRate { get; set; }
        public Nullable<decimal> td_StoreBoilerChemicalPerBagRate { get; set; }
        public Nullable<decimal> od_StoreBoilerChemicalPerTonCaneRate { get; set; }
        public Nullable<decimal> td_StoreBoilerChemicalPerTonCaneRate { get; set; }
        public Nullable<decimal> od_StoreGreaseOilQuantity { get; set; }
        public Nullable<decimal> td_StoreGreaseOilQuantity { get; set; }
        public Nullable<decimal> od_StoreGreaseOilAmount { get; set; }
        public Nullable<decimal> td_StoreGreaseOilAmount { get; set; }
        public Nullable<decimal> od_StoreGreaseOilPerBagRate { get; set; }
        public Nullable<decimal> td_StoreGreaseOilPerBagRate { get; set; }
        public Nullable<decimal> od_StoreGreaseOilPerTonCaneRate { get; set; }
        public Nullable<decimal> td_StoreGreaseOilPerTonCaneRate { get; set; }
        public Nullable<decimal> od_bags_plus_minus { get; set; }
        public Nullable<decimal> td_bags_plus_minus { get; set; }
        public Nullable<decimal> od_molasses_plus_minus { get; set; }
        public Nullable<decimal> td_molasses_plus_minus { get; set; }
        public decimal od_bagasse_baed { get; set; }
        public decimal td_bagasse_baed { get; set; }
        public Nullable<decimal> td_icumsa_raw { get; set; }
        public Nullable<decimal> od_gross_biss_sugar { get; set; }
        public Nullable<decimal> td_gross_biss_sugar { get; set; }
        public Nullable<decimal> od_gross_scrap_sugar { get; set; }
        public Nullable<decimal> td_gross_scrap_sugar { get; set; }
        public Nullable<decimal> od_gross_moist_sugar { get; set; }
        public Nullable<decimal> td_gross_moist_sugar { get; set; }
        public Nullable<decimal> od_gross_raw_sugar { get; set; }
        public Nullable<decimal> td_gross_raw_sugar { get; set; }
        public decimal od_available_biss_sugar { get; set; }
        public Nullable<decimal> td_available_biss_sugar { get; set; }
        public decimal od_available_scrap_sugar { get; set; }
        public Nullable<decimal> td_available_scrap_sugar { get; set; }
        public decimal od_available_moist_sugar { get; set; }
        public Nullable<decimal> td_available_moist_sugar { get; set; }
        public decimal od_available_raw_sugar { get; set; }
        public Nullable<decimal> td_available_raw_sugar { get; set; }
        public decimal od_available_other_sugar { get; set; }
        public Nullable<decimal> td_available_other_sugar { get; set; }
        public decimal od_available_biss_molasses { get; set; }
        public Nullable<decimal> td_available_biss_molasses { get; set; }
        public decimal od_available_scrap_molasses { get; set; }
        public Nullable<decimal> td_available_scrap_molasses { get; set; }
        public decimal od_available_moist_molasses { get; set; }
        public Nullable<decimal> td_available_moist_molasses { get; set; }
        public decimal od_available_raw_molasses { get; set; }
        public Nullable<decimal> td_available_raw_molasses { get; set; }
        public decimal od_available_other_molasses { get; set; }
        public Nullable<decimal> td_available_other_molasses { get; set; }
        public Nullable<decimal> od_diverted_syrup_pol_qtl { get; set; }
        public int td_diverted_syrup_pol_qtl { get; set; }
        public Nullable<decimal> od_syrup_diversion { get; set; }
        public Nullable<decimal> td_syrup_diversion { get; set; }
        public Nullable<decimal> od_diverted_syrup_percent_cane { get; set; }
        public Nullable<decimal> td_diverted_syrup_percent_cane { get; set; }
        public Nullable<decimal> od_unknown_losses_calculated { get; set; }
        public Nullable<decimal> td_unknown_losses_calculated { get; set; }
        public Nullable<decimal> od_unknown_losses_calculated_percent { get; set; }
        public Nullable<decimal> td_unknown_losses_calculated_percent { get; set; }
        public Nullable<decimal> od_cane_used_for_syrup { get; set; }
        public Nullable<decimal> td_cane_used_for_syrup { get; set; }
        public Nullable<decimal> od_cane_percent_used_for_syrup { get; set; }
        public Nullable<decimal> td_cane_percent_used_for_syrup { get; set; }
        public Nullable<decimal> od_estimated_sugar_percent_on_c_heavy { get; set; }
        public Nullable<decimal> td_estimated_sugar_percent_on_c_heavy { get; set; }
        public Nullable<decimal> od_estimated_sugar_percent_on_raw_sugar { get; set; }
        public Nullable<decimal> td_estimated_sugar_percent_on_raw_sugar { get; set; }
        public Nullable<decimal> od_estimated_sugar_percent_on_b_heavy { get; set; }
        public Nullable<decimal> td_estimated_sugar_percent_on_b_heavy { get; set; }
        public Nullable<decimal> od_estimated_sugar_percent_on_syrup { get; set; }
        public Nullable<decimal> td_estimated_sugar_percent_on_syrup { get; set; }
        public Nullable<decimal> od_molasses_by_cane_used_for_sugar_production { get; set; }
        public Nullable<decimal> td_molasses_by_cane_used_for_sugar_production { get; set; }
        public System.DateTime report_compiled_at { get; set; }
        public Nullable<decimal> od_power_to_distillery { get; set; }
        public Nullable<decimal> td_power_to_distillery { get; set; }
        public Nullable<decimal> od_rectified_sprit { get; set; }
        public Nullable<decimal> td_rectified_sprit { get; set; }
        public Nullable<decimal> od_rectified_sprit_recovery { get; set; }
        public Nullable<decimal> td_rectified_sprit_recovery { get; set; }
        public Nullable<decimal> od_absolute_alcohol { get; set; }
        public Nullable<decimal> td_absolute_alcohol { get; set; }
        public Nullable<decimal> od_absolute_alcohol_recovery { get; set; }
        public Nullable<decimal> td_absolute_alcohol_recovery { get; set; }
        public Nullable<decimal> od_ethanol { get; set; }
        public Nullable<decimal> td_ethanol { get; set; }
        public Nullable<decimal> od_ethanol_recovery { get; set; }
        public Nullable<decimal> td_ethanol_recovery { get; set; }
        public Nullable<decimal> month_rectified_spirit { get; set; }
        public Nullable<decimal> month_absolute_alcohol { get; set; }
        public Nullable<decimal> month_ethanol { get; set; }
        public Nullable<decimal> month_power_generation_co_gen { get; set; }
        public Nullable<decimal> month_power_export_co_gen { get; set; }
        public Nullable<decimal> month_power_export_distillery { get; set; }
        public Nullable<decimal> od_power_export_from_co_gen { get; set; }
        public Nullable<decimal> td_power_export_from_co_gen { get; set; }
        public Nullable<decimal> od_power_export_from_distillery { get; set; }
        public Nullable<decimal> td_power_export_from_distillery { get; set; }
        public Nullable<decimal> month_distillery_total_production { get; set; }
        public Nullable<decimal> month_power_to_distillery { get; set; }
        public Nullable<decimal> od_pol_in_syup_percent_cane { get; set; }
        public Nullable<decimal> td_pol_in_syup_percent_cane { get; set; }
        public Nullable<decimal> od_new_mill_crush { get; set; }
        public Nullable<decimal> td_new_mill_crush { get; set; }
        public Nullable<decimal> od_old_mill_crush { get; set; }
        public Nullable<decimal> td_old_mill_crush { get; set; }
        public Nullable<decimal> od_ash_sold { get; set; }
        public Nullable<decimal> td_ash_sold { get; set; }
        public string remarks { get; set; }
        public Nullable<decimal> od_absolute_alcohol_by_syrup { get; set; }
        public Nullable<decimal> td_absolute_alcohol_by_syrup { get; set; }
        public decimal od_absolute_alcohol_by_b_heavy { get; set; }
        public Nullable<decimal> td_absolute_alcohol_by_b_heavy { get; set; }
        public decimal od_absolute_alcohol_by_c_heavy { get; set; }
        public Nullable<decimal> td_absolute_alcohol_by_c_heavy { get; set; }
        public Nullable<decimal> od_absolute_alcohol_by_syruprecovery { get; set; }
        public Nullable<decimal> td_absolute_alcohol_by_syrup_recovery { get; set; }
        public Nullable<decimal> od_absolute_alcohol_by_b_heavy_recovery { get; set; }
        public Nullable<decimal> td_absolute_alcohol_by_b_heavy_recovery { get; set; }
        public Nullable<decimal> od_absolute_alcohol_by_c_heavy_recovery { get; set; }
        public Nullable<decimal> td_absolute_alcohol_by_c_heavyrecovery { get; set; }
        public decimal od_ph_boiler_water { get; set; }
        public decimal od_ph_injection_outlet { get; set; }
        public Nullable<decimal> month_absolute_alcohol_by_syrup { get; set; }
        public Nullable<decimal> month_absolute_alcohol_by_b_heavy { get; set; }
        public Nullable<decimal> month_absolute_alcohol_by_c_heavy { get; set; }
        public Nullable<decimal> month_bagasse_sold { get; set; }
        public Nullable<decimal> month_ash_sold { get; set; }
        public decimal od_material_sent_out_c_heavy_purity { get; set; }
        public decimal od_power_from_sugar1 { get; set; }
        public Nullable<decimal> td_power_export_from_sugar { get; set; }
    }
}