//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaneAnalys
    {
        public int Id { get; set; }
        public int UnitCode { get; set; }
        public System.DateTime SampleDate { get; set; }
        public System.DateTime AnalysisDate { get; set; }
        public int ZoneCode { get; set; }
        public int VillageCode { get; set; }
        public int GrowerCode { get; set; }
        public int VarietyCode { get; set; }
        public int CaneType { get; set; }
        public int LandPosition { get; set; }
        public string FieldCondition { get; set; }
        public Nullable<decimal> JuicePercent { get; set; }
        public Nullable<decimal> Brix { get; set; }
        public Nullable<decimal> Pol { get; set; }
        public Nullable<decimal> Purity { get; set; }
        public Nullable<decimal> PolInCaneToday { get; set; }
        public Nullable<decimal> RecoveryByWCapToday { get; set; }
        public Nullable<decimal> RecoveryByMolPurityToday { get; set; }
        public Nullable<System.DateTime> PreviousSeasonHarvestingDate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public int SeasonCode { get; set; }
        public Nullable<int> IrrigatedDays { get; set; }
        public Nullable<decimal> MaxTemperature { get; set; }
        public Nullable<decimal> MinTemperature { get; set; }
        public Nullable<decimal> Humidity { get; set; }
    }
}
