//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataAdjustment
    {
        public int id { get; set; }
        public Nullable<int> a_unit_code { get; set; }
        public Nullable<int> a_season_code { get; set; }
        public System.DateTime a_entry_date { get; set; }
        public Nullable<decimal> a_sulpher { get; set; }
        public Nullable<decimal> a_lime { get; set; }
        public Nullable<decimal> a_phosphoric_acid { get; set; }
        public Nullable<decimal> a_color_reducer { get; set; }
        public Nullable<decimal> a_megnafloe { get; set; }
        public Nullable<decimal> a_lub_oil { get; set; }
        public Nullable<decimal> a_viscosity_reducer { get; set; }
        public Nullable<decimal> a_biocide { get; set; }
        public Nullable<decimal> a_lub_greace { get; set; }
        public Nullable<decimal> a_boiler_chemical { get; set; }
        public Nullable<decimal> a_estimated_sugar { get; set; }
        public Nullable<decimal> a_estimated_molasses { get; set; }
        public decimal a_washing_soda { get; set; }
        public decimal a_hydrolic_soda { get; set; }
        public decimal a_de_scaling_chemical { get; set; }
        public decimal a_seed_slurry { get; set; }
        public decimal a_anti_fomer { get; set; }
        public decimal a_chemical_for_brs_cleaning { get; set; }
        public bool a_is_active { get; set; }
        public System.DateTime crtd_dt { get; set; }
        public Nullable<System.DateTime> updt_dt { get; set; }
        public string crtd_by { get; set; }
        public string updt_by { get; set; }
        public Nullable<decimal> EstimatedCaneForSyrupDiversion { get; set; }
    
        public virtual MasterUnit MasterUnit { get; set; }
        public virtual MasterUnit MasterUnit1 { get; set; }
    }
}
