//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailConfiguration
    {
        public int Id { get; set; }
        public string EmailAddress { get; set; }
        public string Salt { get; set; }
        public string Password { get; set; }
        public int SmtpPort { get; set; }
        public string SmtpHost { get; set; }
        public bool EnabledSSL { get; set; }
        public bool IsActive { get; set; }
        public string ApiKey { get; set; }
        public Nullable<int> PrioritySequence { get; set; }
    }
}
