//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string FileName { get; set; }
        public string StackTrace { get; set; }
        public string ErrorCode { get; set; }
        public string InnerException { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> ExceptionOccuredAt { get; set; }
        public Nullable<bool> ExceptionSolved { get; set; }
        public Nullable<System.DateTime> ExceptionSolvedAt { get; set; }
        public string ExceptionSolvedBy { get; set; }
    }
}
