//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelReportTemplate
    {
        public int Id { get; set; }
        public int ReportCode { get; set; }
        public int DataType { get; set; }
        public string CellFrom { get; set; }
        public string CellTo { get; set; }
        public string Value { get; set; }
        public bool Bold { get; set; }
        public bool Italic { get; set; }
        public string FontColor { get; set; }
        public string BackGroundColor { get; set; }
        public string NumerFormat { get; set; }
        public string HelpText { get; set; }
    
        public virtual ExcelReportDataType ExcelReportDataType { get; set; }
        public virtual ReportDetail ReportDetail { get; set; }
    }
}
