//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirebaseNotificationRight
    {
        public int id { get; set; }
        public int NotificationCode { get; set; }
        public string UserCode { get; set; }
        public string UnitRights { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual FirebaseNotificationType FirebaseNotificationType { get; set; }
    }
}
