//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grower
    {
        public int Id { get; set; }
        public int UnitCode { get; set; }
        public int VillageCode { get; set; }
        public int Code { get; set; }
        public string UniqueCode { get; set; }
        public string Name { get; set; }
        public string RelativeName { get; set; }
        public string FlexRelationCode { get; set; }
        public string MobileNo { get; set; }
        public string Uid { get; set; }
        public bool IsActive { get; set; }
    }
}
