//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HourlyAnalys
    {
        public long id { get; set; }
        public int unit_code { get; set; }
        public int season_code { get; set; }
        public System.DateTime entry_Date { get; set; }
        public int entry_time { get; set; }
        public Nullable<int> new_mill_juice { get; set; }
        public Nullable<int> old_mill_juice { get; set; }
        public Nullable<int> juice_total { get; set; }
        public Nullable<int> new_mill_water { get; set; }
        public Nullable<int> old_mill_water { get; set; }
        public Nullable<int> water_total { get; set; }
        public Nullable<int> sugar_bags_L31 { get; set; }
        public Nullable<int> sugar_bags_L30 { get; set; }
        public Nullable<int> sugar_bags_L_total { get; set; }
        public Nullable<int> sugar_bags_M31 { get; set; }
        public Nullable<int> sugar_bags_M30 { get; set; }
        public Nullable<int> sugar_bags_M_total { get; set; }
        public Nullable<int> sugar_bags_S31 { get; set; }
        public Nullable<int> sugar_bags_S30 { get; set; }
        public Nullable<int> sugar_bags_S_total { get; set; }
        public Nullable<int> sugar_Biss { get; set; }
        public Nullable<int> sugar_raw { get; set; }
        public Nullable<int> sugar_bags_total { get; set; }
        public string cooling_trace { get; set; }
        public decimal cooling_pol { get; set; }
        public decimal cooling_ph { get; set; }
        public Nullable<System.DateTime> crtd_dt { get; set; }
        public string crtd_by { get; set; }
        public Nullable<System.DateTime> updt_dt { get; set; }
        public string updt_by { get; set; }
        public short standing_truck { get; set; }
        public short standing_trippler { get; set; }
        public short standing_trolley { get; set; }
        public short standing_cart { get; set; }
        public Nullable<decimal> un_crushed_cane { get; set; }
        public Nullable<decimal> crushed_cane { get; set; }
        public decimal cane_diverted_for_syrup { get; set; }
        public decimal diverted_syrup_quantity { get; set; }
        public int export_sugar { get; set; }
    }
}
