//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeySampleAnalys
    {
        public int id { get; set; }
        public Nullable<int> unit_code { get; set; }
        public short pan_number { get; set; }
        public System.DateTime entry_date { get; set; }
        public System.TimeSpan entry_time { get; set; }
        public int sugar_stage { get; set; }
        public decimal brix { get; set; }
        public decimal pol { get; set; }
        public decimal purity { get; set; }
        public string crtd_by { get; set; }
        public System.DateTime crtd_dt { get; set; }
        public int season_code { get; set; }
    
        public virtual MasterParameterSubCategory MasterParameterSubCategory { get; set; }
        public virtual MasterUnit MasterUnit { get; set; }
    }
}
