//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MassecuiteAnalys
    {
        public long id { get; set; }
        public Nullable<int> unit_code { get; set; }
        public Nullable<int> season_code { get; set; }
        public int m_param_type_code { get; set; }
        public Nullable<System.DateTime> m_entry_date { get; set; }
        public System.TimeSpan m_entry_time { get; set; }
        public decimal m_hl { get; set; }
        public decimal m_pan_no { get; set; }
        public System.TimeSpan m_start_time { get; set; }
        public System.TimeSpan m_drop_time { get; set; }
        public int m_crystal_no { get; set; }
        public decimal m_brix { get; set; }
        public decimal m_pol { get; set; }
        public decimal m_purity { get; set; }
        public System.DateTime crtd_dt { get; set; }
        public string crtd_by { get; set; }
        public Nullable<decimal> m_icumsa_unit { get; set; }
    
        public virtual MasterParameterSubCategory MasterParameterSubCategory { get; set; }
    }
}
