//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterStoppageSubType
    {
        public int Code { get; set; }
        public Nullable<int> MasterStoppageCode { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public int SubStoppageGroup { get; set; }
        public int StoppageType { get; set; }
    
        public virtual MasterStoppageType MasterStoppageType { get; set; }
        public virtual StoppageType StoppageType1 { get; set; }
    }
}
