//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterUnit()
        {
            this.KeySampleAnalyses = new HashSet<KeySampleAnalys>();
            this.MasterUnitAuthorities = new HashSet<MasterUnitAuthority>();
            this.MasterVehicles = new HashSet<MasterVehicle>();
            this.MeltingAnalyses = new HashSet<MeltingAnalys>();
            this.MolassesAnalyses = new HashSet<MolassesAnalys>();
            this.UserRights = new HashSet<UserRight>();
            this.UnitSeasons = new HashSet<UnitSeason>();
            this.ValidationParameters = new HashSet<ValidationParameter>();
            this.PeriodicalStocks = new HashSet<PeriodicalStock>();
            this.Villages = new HashSet<Village>();
            this.Zones = new HashSet<Zone>();
            this.DataAdjustments = new HashSet<DataAdjustment>();
            this.DataAdjustments1 = new HashSet<DataAdjustment>();
            this.MasterUsers = new HashSet<MasterUser>();
            this.DailyAnalyses = new HashSet<DailyAnalys>();
        }
    
        public int Id { get; set; }
        public byte CompanyCode { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int CrushingSeason { get; set; }
        public System.DateTime CrushingStartDate { get; set; }
        public Nullable<System.DateTime> CrushingEndDate { get; set; }
        public Nullable<int> DayHours { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.DateTime ProcessDate { get; set; }
        public Nullable<decimal> NewMillCapacity { get; set; }
        public Nullable<decimal> OldMillCapacity { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Createdy { get; set; }
        public int ReportStartTime { get; set; }
        public Nullable<int> CrushingStartTime { get; set; }
        public Nullable<int> CrushingEndTime { get; set; }
        public Nullable<int> AllowedModificationDays { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> CrushingStartDateTime { get; set; }
        public Nullable<System.DateTime> CrushingEndDateTime { get; set; }
        public Nullable<System.TimeSpan> ReportStartHourMinute { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeySampleAnalys> KeySampleAnalyses { get; set; }
        public virtual MasterCompany MasterCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterUnitAuthority> MasterUnitAuthorities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterVehicle> MasterVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeltingAnalys> MeltingAnalyses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MolassesAnalys> MolassesAnalyses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRight> UserRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitSeason> UnitSeasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValidationParameter> ValidationParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeriodicalStock> PeriodicalStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Village> Villages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zone> Zones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataAdjustment> DataAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataAdjustment> DataAdjustments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterUser> MasterUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyAnalys> DailyAnalyses { get; set; }
    }
}
