//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeltingAnalys
    {
        public int id { get; set; }
        public Nullable<int> unit_code { get; set; }
        public Nullable<int> season_code { get; set; }
        public int m_code { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<System.TimeSpan> entry_time { get; set; }
        public decimal brix { get; set; }
        public decimal pol { get; set; }
        public decimal purity { get; set; }
        public System.DateTime crtd_dt { get; set; }
        public string crtd_by { get; set; }
        public Nullable<System.DateTime> updt_dt { get; set; }
        public string updt_by { get; set; }
        public Nullable<decimal> icumsa_unit { get; set; }
    
        public virtual MasterParameterSubCategory MasterParameterSubCategory { get; set; }
        public virtual MasterUnit MasterUnit { get; set; }
    }
}
