//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileDevice
    {
        public string ImeiNumber { get; set; }
        public Nullable<decimal> MobileNumber { get; set; }
        public string DeviceToken { get; set; }
        public string UserCode { get; set; }
        public string UserImageUrl { get; set; }
        public string CompanyImageUrl { get; set; }
        public string UnitRights { get; set; }
        public string MenuRights { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
    }
}
