//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MolassesAnalys
    {
        public int id { get; set; }
        public Nullable<int> Unit_Code { get; set; }
        public Nullable<int> season_code { get; set; }
        public System.DateTime mo_entry_date { get; set; }
        public string mo_entry_time { get; set; }
        public int mo_code { get; set; }
        public decimal mo_brix { get; set; }
        public decimal mo_pol { get; set; }
        public decimal mo_purity { get; set; }
        public System.DateTime mo_crtd_date { get; set; }
        public string mo_crtd_by { get; set; }
        public Nullable<System.DateTime> mo_updt_dt { get; set; }
        public string mo_updt_by { get; set; }
        public Nullable<decimal> mo_icumsa_unit { get; set; }
    
        public virtual MasterParameterSubCategory MasterParameterSubCategory { get; set; }
        public virtual MasterUnit MasterUnit { get; set; }
    }
}
