//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordReset
    {
        public int Id { get; set; }
        public string UserCode { get; set; }
        public string Url { get; set; }
        public string Token { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTill { get; set; }
        public bool IsActive { get; set; }
        public string RequestIP { get; set; }
    }
}
