//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodicalStock
    {
        public System.Guid Id { get; set; }
        public int UnitCode { get; set; }
        public int SeasonCode { get; set; }
        public System.DateTime EntryDate { get; set; }
        public decimal MixedJuiceJuiceHl { get; set; }
        public decimal MixedJuiceJuiceBrix { get; set; }
        public decimal MixedJuiceJuicePol { get; set; }
        public decimal MixedJuiceJuicePurity { get; set; }
        public decimal MixedJuiceJuiceAvailableSugar { get; set; }
        public decimal MixedJuiceJuiceAvailableMolasses { get; set; }
        public decimal ClearJuiceHl { get; set; }
        public decimal ClearJuiceBrix { get; set; }
        public decimal ClearJuicePol { get; set; }
        public decimal ClearJuicePurity { get; set; }
        public decimal ClearJuiceAvailableSugar { get; set; }
        public decimal ClearJuiceAvailableMolasses { get; set; }
        public decimal SyrupJuiceHl { get; set; }
        public decimal SyrupJuiceBrix { get; set; }
        public decimal SyrupJuicePol { get; set; }
        public decimal SyrupJuicePurity { get; set; }
        public decimal SyrupJuiceAvailableSugar { get; set; }
        public decimal SyrupJuiceAvailableMolasses { get; set; }
        public decimal SeedJuiceHl { get; set; }
        public decimal SeedJuiceBrix { get; set; }
        public decimal SeedJuicePol { get; set; }
        public decimal SeedJuicePurity { get; set; }
        public decimal SeedJuiceAvailableSugar { get; set; }
        public decimal SeedJuiceAvailableMolasses { get; set; }
        public decimal MassecuiteAJuiceHl { get; set; }
        public decimal MassecuiteAJuiceBrix { get; set; }
        public decimal MassecuiteAJuicePol { get; set; }
        public decimal MassecuiteAJuicePurity { get; set; }
        public decimal MassecuiteAJuiceAvailableSugar { get; set; }
        public decimal MassecuiteAJuiceAvailableMolasses { get; set; }
        public decimal MassecuiteCJuiceHl { get; set; }
        public decimal MassecuiteCJuiceBrix { get; set; }
        public decimal MassecuiteCJuicePol { get; set; }
        public decimal MassecuiteCJuicePurity { get; set; }
        public decimal MassecuiteCJuiceAvailableSugar { get; set; }
        public decimal MassecuiteCJuiceAvailableMolasses { get; set; }
        public decimal MassecuiteCOneJuiceHl { get; set; }
        public decimal MassecuiteCOneJuiceBrix { get; set; }
        public decimal MassecuiteCOneJuicePol { get; set; }
        public decimal MassecuiteCOneJuicePurity { get; set; }
        public decimal MassecuiteCOneJuiceAvailableSugar { get; set; }
        public decimal MassecuiteCOneJuiceAvailableMolasses { get; set; }
        public decimal MassecuiteROneJuiceHl { get; set; }
        public decimal MassecuiteROneJuiceBrix { get; set; }
        public decimal MassecuiteROneJuicePol { get; set; }
        public decimal MassecuiteROneJuicePurity { get; set; }
        public decimal MassecuiteROneJuiceAvailableSugar { get; set; }
        public decimal MassecuiteROneJuiceAvailableMolasses { get; set; }
        public decimal MassecuiteBJuiceHl { get; set; }
        public decimal MassecuiteBJuiceBrix { get; set; }
        public decimal MassecuiteBJuicePol { get; set; }
        public decimal MassecuiteBJuicePurity { get; set; }
        public decimal MassecuiteBJuiceAvailableSugar { get; set; }
        public decimal MassecuiteBJuiceAvailableMolasses { get; set; }
        public decimal MassecuiteRTwoJuiceHl { get; set; }
        public decimal MassecuiteRTwoJuiceBrix { get; set; }
        public decimal MassecuiteRTwoJuicePol { get; set; }
        public decimal MassecuiteRTwoJuicePurity { get; set; }
        public decimal MassecuiteRTwoJuiceAvailableSugar { get; set; }
        public decimal MassecuiteRTwoJuiceAvailableMolasses { get; set; }
        public decimal MassecuiteRThreeJuiceHl { get; set; }
        public decimal MassecuiteRThreeJuiceBrix { get; set; }
        public decimal MassecuiteRThreeJuicePol { get; set; }
        public decimal MassecuiteRThreeJuicePurity { get; set; }
        public decimal MassecuiteRThreeJuiceAvailableSugar { get; set; }
        public decimal MassecuiteRThreeJuiceAvailableMolasses { get; set; }
        public decimal MolassesAHeavyJuiceHl { get; set; }
        public decimal MolassesAHeavyJuiceBrix { get; set; }
        public decimal MolassesAHeavyJuicePol { get; set; }
        public decimal MolassesAHeavyJuicePurity { get; set; }
        public decimal MolassesAHeavyJuiceAvailableSugar { get; set; }
        public decimal MolassesAHeavyJuiceAvailableMolasses { get; set; }
        public decimal MolassesALightJuiceHl { get; set; }
        public decimal MolassesALightJuiceBrix { get; set; }
        public decimal MolassesALightJuicePol { get; set; }
        public decimal MolassesALightJuicePurity { get; set; }
        public decimal MolassesALightJuiceAvailableSugar { get; set; }
        public decimal MolassesALightJuiceAvailableMolasses { get; set; }
        public decimal MolassesBHeavyJuiceHl { get; set; }
        public decimal MolassesBHeavyJuiceBrix { get; set; }
        public decimal MolassesBHeavyJuicePol { get; set; }
        public decimal MolassesBHeavyJuicePurity { get; set; }
        public decimal MolassesBHeavyJuiceAvailableSugar { get; set; }
        public decimal MolassesBHeavyJuiceAvailableMolasses { get; set; }
        public decimal MolassesCLightJuiceHl { get; set; }
        public decimal MolassesCLightJuiceBrix { get; set; }
        public decimal MolassesCLightJuicePol { get; set; }
        public decimal MolassesCLightJuicePurity { get; set; }
        public decimal MolassesCLightJuiceAvailableSugar { get; set; }
        public decimal MolassesCLightJuiceAvailableMolasses { get; set; }
        public decimal MolassesCOneJuiceHl { get; set; }
        public decimal MolassesCOneJuiceBrix { get; set; }
        public decimal MolassesCOneJuicePol { get; set; }
        public decimal MolassesCOneJuicePurity { get; set; }
        public decimal MolassesCOneJuiceAvailableSugar { get; set; }
        public decimal MolassesCOneJuiceAvailableMolasses { get; set; }
        public decimal MolassesROneHeavyJuiceHl { get; set; }
        public decimal MolassesROneHeavyJuiceBrix { get; set; }
        public decimal MolassesROneHeavyJuicePol { get; set; }
        public decimal MolassesROneHeavyJuicePurity { get; set; }
        public decimal MolassesROneHeavyJuiceAvailableSugar { get; set; }
        public decimal MolassesROneHeavyJuiceAvailableMolasses { get; set; }
        public decimal MolassesRTwoJuiceHl { get; set; }
        public decimal MolassesRTwoJuiceBrix { get; set; }
        public decimal MolassesRTwoJuicePol { get; set; }
        public decimal MolassesRTwoJuicePurity { get; set; }
        public decimal MolassesRTwoJuiceAvailableSugar { get; set; }
        public decimal MolassesRTwoJuiceAvailableMolasses { get; set; }
        public decimal MolassesRThreeHeavyJuiceHl { get; set; }
        public decimal MolassesRThreeHeavyJuiceBrix { get; set; }
        public decimal MolassesRThreeHeavyJuicePol { get; set; }
        public decimal MolassesRThreeHeavyJuicePurity { get; set; }
        public decimal MolassesRThreeHeavyJuiceAvailableSugar { get; set; }
        public decimal MolassesRThreeHeavyJuiceAvailableMolasses { get; set; }
        public decimal SugarUnweightedJuiceHl { get; set; }
        public decimal SugarUnweightedJuiceBrix { get; set; }
        public decimal SugarUnweightedJuicePol { get; set; }
        public decimal SugarUnweightedJuicePurity { get; set; }
        public decimal SugarUnweightedJuiceAvailableSugar { get; set; }
        public decimal SugarUnweightedJuiceAvailableMolasses { get; set; }
        public decimal FineLiqorJuiceHl { get; set; }
        public decimal FineLiqorJuiceBrix { get; set; }
        public decimal FineLiqorJuicePol { get; set; }
        public decimal FineLiqorJuicePurity { get; set; }
        public decimal FineLiqorJuiceAvailableSugar { get; set; }
        public decimal FineLiqorJuiceAvailableMolasses { get; set; }
        public decimal TotalJuiceHl { get; set; }
        public decimal TotalJuiceBrix { get; set; }
        public decimal TotalJuicePol { get; set; }
        public decimal TotalJuicePurity { get; set; }
        public decimal TotalJuiceAvailableSugar { get; set; }
        public decimal TotalJuiceAvailableMolasses { get; set; }
        public decimal BagasseSaved { get; set; }
        public decimal BagasseToDistillery { get; set; }
        public decimal BagassePurchased { get; set; }
        public bool IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual MasterSeason MasterSeason { get; set; }
        public virtual MasterUnit MasterUnit { get; set; }
    }
}
