//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessedAdditionalData
    {
        public System.Guid Id { get; set; }
        public int UnitCode { get; set; }
        public int SeasonCode { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<decimal> Icumsa_L31_Qtl { get; set; }
        public Nullable<decimal> Icumsa_L30_Qtl { get; set; }
        public Nullable<decimal> Icumsa_M31_Qtl { get; set; }
        public Nullable<decimal> Icumsa_M30_Qtl { get; set; }
        public Nullable<decimal> Icumsa_S31_Qtl { get; set; }
        public Nullable<decimal> Icumsa_S30_Qtl { get; set; }
        public Nullable<decimal> Icumsa_RawSugar { get; set; }
        public Nullable<decimal> ForeignMatter_L31_Qtl { get; set; }
        public Nullable<decimal> ForeignMatter_L30_Qtl { get; set; }
        public Nullable<decimal> ForeignMatter_M31_Qtl { get; set; }
        public Nullable<decimal> ForeignMatter_M30_Qtl { get; set; }
        public Nullable<decimal> ForeignMatter_S31_Qtl { get; set; }
        public Nullable<decimal> ForeignMatter_S30_Qtl { get; set; }
        public Nullable<decimal> ForeignMatter_RawSugar { get; set; }
        public Nullable<decimal> Retention_L31_Qtl { get; set; }
        public Nullable<decimal> Retention_L30_Qtl { get; set; }
        public Nullable<decimal> Retention_M31_Qtl { get; set; }
        public Nullable<decimal> Retention_M30_Qtl { get; set; }
        public Nullable<decimal> Retention_S31_Qtl { get; set; }
        public Nullable<decimal> Retention_S30_Qtl { get; set; }
        public Nullable<decimal> Retention_RawSugar { get; set; }
        public Nullable<decimal> Moisture_L31_Qtl { get; set; }
        public Nullable<decimal> Moisture_L30_Qtl { get; set; }
        public Nullable<decimal> Moisture_M31_Qtl { get; set; }
        public Nullable<decimal> Moisture_M30_Qtl { get; set; }
        public Nullable<decimal> Moisture_S31_Qtl { get; set; }
        public Nullable<decimal> Moisture_S30_Qtl { get; set; }
        public Nullable<decimal> Moisture_RawSugar { get; set; }
    }
}
