//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredDevice
    {
        public string Code { get; set; }
        public string Gender { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ImageUrl { get; set; }
        public string UserCode { get; set; }
        public string UserPassword { get; set; }
        public string Salt { get; set; }
        public int DeviceTypeCode { get; set; }
        public string DeviceToken { get; set; }
        public string AccessToken { get; set; }
        public string UnitRights { get; set; }
        public string MenuRights { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTill { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public int DepartmentCode { get; set; }
        public string Email { get; set; }
    
        public virtual MasterDeviceType MasterDeviceType { get; set; }
        public virtual MasterDepartment MasterDepartment { get; set; }
    }
}
