//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportDetail()
        {
            this.ExcelReportTemplates = new HashSet<ExcelReportTemplate>();
        }
    
        public int Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Formats { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<byte> ReportSchemaCode { get; set; }
        public string ReportCategory { get; set; }
        public Nullable<bool> IsTemplateBased { get; set; }
        public string TemplatePath { get; set; }
        public string TemplateFileName { get; set; }
        public Nullable<int> NoOfPages { get; set; }
        public bool AdminOnly { get; set; }
        public string FileGenerationLocation { get; set; }
        public Nullable<bool> AllowAutoGenerate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcelReportTemplate> ExcelReportTemplates { get; set; }
        public virtual ReportSchema ReportSchema { get; set; }
    }
}
