//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportAwaiting
    {
        public int Id { get; set; }
        public Nullable<int> UnitCode { get; set; }
        public Nullable<int> SeasonCode { get; set; }
        public Nullable<int> ReportCode { get; set; }
        public Nullable<System.DateTime> ReportForDate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public int ReportStatusCode { get; set; }
        public bool HasError { get; set; }
        public string ErrorMessage { get; set; }
    }
}
