//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stoppage
    {
        public int id { get; set; }
        public Nullable<int> unit_code { get; set; }
        public System.DateTime s_date { get; set; }
        public Nullable<int> season_code { get; set; }
        public System.DateTime s_start_calendar_date { get; set; }
        public string s_start_time { get; set; }
        public Nullable<System.DateTime> s_end_calendar_date { get; set; }
        public string s_end_time { get; set; }
        public Nullable<int> s_duration { get; set; }
        public Nullable<decimal> s_net_duration { get; set; }
        public int s_mill_code { get; set; }
        public int s_head_code { get; set; }
        public string s_head_name { get; set; }
        public int s_sub_head_code { get; set; }
        public string s_sub_head_name { get; set; }
        public string s_comment { get; set; }
        public string s_crtd_by { get; set; }
        public Nullable<System.DateTime> s_crtd_dt { get; set; }
        public string s_updt_by { get; set; }
        public Nullable<System.DateTime> s_updt_dt { get; set; }
        public byte sent_sms_count { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    }
}
