//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwoHourlyAnalys
    {
        public long Id { get; set; }
        public Nullable<int> Unit_Code { get; set; }
        public Nullable<int> season_code { get; set; }
        public System.DateTime Entry_Date { get; set; }
        public int entry_Time { get; set; }
        public decimal NM_Primary_Juice_Brix { get; set; }
        public decimal NM_Primary_juice_pol { get; set; }
        public decimal nm_primary_juice_purity { get; set; }
        public decimal nm_primary_juice_ph { get; set; }
        public decimal om_primary_juice_brix { get; set; }
        public decimal om_primary_juice_pol { get; set; }
        public decimal om_primary_juice_purity { get; set; }
        public decimal om_primary_juice_ph { get; set; }
        public decimal nm_mixed_juice_brix { get; set; }
        public decimal nm_mixed_juice_pol { get; set; }
        public decimal nm_mixed_juice_purity { get; set; }
        public decimal nm_mixed_juice_ph { get; set; }
        public decimal om_mixed_juice_brix { get; set; }
        public decimal om_mixed_juice_pol { get; set; }
        public decimal om_mixed_juice_purity { get; set; }
        public decimal om_mixed_juice_ph { get; set; }
        public decimal nm_last_juice_brix { get; set; }
        public decimal nm_last_juice_pol { get; set; }
        public decimal nm_last_juice_purity { get; set; }
        public decimal om_last_juice_brix { get; set; }
        public decimal om_last_juice_pol { get; set; }
        public decimal om_last_juice_purity { get; set; }
        public decimal oliver_juice_brix { get; set; }
        public decimal oliver_juice_pol { get; set; }
        public decimal oliver_juice_ph { get; set; }
        public decimal oliver_juice_purity { get; set; }
        public decimal fcs_juice_brix { get; set; }
        public decimal fcs_juice_pol { get; set; }
        public decimal fcs_juice_ph { get; set; }
        public decimal fcs_juice_purity { get; set; }
        public decimal clear_juice_brix { get; set; }
        public decimal clear_juice_pol { get; set; }
        public decimal clear_juice_ph { get; set; }
        public decimal clear_juice_purity { get; set; }
        public decimal unsulphured_syrup_brix { get; set; }
        public decimal unsulphured_syrup_pol { get; set; }
        public decimal unsulphured_syrup_ph { get; set; }
        public decimal unsulphured_syrup_purity { get; set; }
        public decimal sulphured_syrup_brix { get; set; }
        public decimal sulphured_syrup_pol { get; set; }
        public decimal sulphured_syrup_ph { get; set; }
        public decimal sulphured_syrup_purity { get; set; }
        public decimal final_molasses_brix { get; set; }
        public decimal final_molasses_pol { get; set; }
        public decimal final_molasses_purity { get; set; }
        public decimal final_molasses_temp { get; set; }
        public decimal final_molasses_tanks { get; set; }
        public decimal nm_bagasse_pol { get; set; }
        public decimal nm_bagasse_moisture { get; set; }
        public decimal om_bagasse_pol { get; set; }
        public decimal om_bagasse_moisture { get; set; }
        public decimal pol_pressure_cake_sample1 { get; set; }
        public decimal pol_pressure_cake_sample2 { get; set; }
        public decimal pol_pressure_cake_sample3 { get; set; }
        public decimal pol_pressure_cake_sample4 { get; set; }
        public decimal pol_pressure_cake_sample5 { get; set; }
        public decimal pol_pressure_cake_sample6 { get; set; }
        public decimal pol_pressure_cake_average { get; set; }
        public decimal pol_pressure_cake_moisture { get; set; }
        public decimal pol_pressure_cake_composite { get; set; }
        public System.DateTime crtd_dt { get; set; }
        public string crtd_by { get; set; }
    }
}
