//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitSeason
    {
        public System.Guid id { get; set; }
        public int Code { get; set; }
        public int Season { get; set; }
        public Nullable<System.DateTime> CrushingStartDateTime { get; set; }
        public Nullable<System.DateTime> CrushingEndDateTime { get; set; }
        public Nullable<decimal> NewMillCapacity { get; set; }
        public Nullable<decimal> OldMillCapacity { get; set; }
        public Nullable<System.TimeSpan> ReportStartHourMinute { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public bool DisableDailyProcess { get; set; }
        public bool DisableAdd { get; set; }
        public bool DisableUpdate { get; set; }
    
        public virtual MasterSeason MasterSeason { get; set; }
        public virtual MasterUnit MasterUnit { get; set; }
    }
}
