//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVerification
    {
        public int Id { get; set; }
        public Nullable<int> UnitCode { get; set; }
        public Nullable<int> season_code { get; set; }
        public string UserCode { get; set; }
        public string ActivationLink { get; set; }
        public string ActivationCode { get; set; }
        public System.DateTime ActivationValidity { get; set; }
        public Nullable<System.DateTime> ActivatedAt { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Token { get; set; }
    }
}
