//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidationParameter
    {
        public int id { get; set; }
        public int UnitCode { get; set; }
        public string Code { get; set; }
        public string MinimumValue { get; set; }
        public string MaximumValue { get; set; }
        public string MinimumEntryCount { get; set; }
        public string MaximumEntryCount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual MasterUnit MasterUnit { get; set; }
    }
}
