//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherRecord
    {
        public int Id { get; set; }
        public int UnitCode { get; set; }
        public int SeasonCode { get; set; }
        public System.DateTime RecordDate { get; set; }
        public Nullable<decimal> TemperatureMin { get; set; }
        public Nullable<decimal> TemperatureMax { get; set; }
        public Nullable<decimal> Humidity { get; set; }
        public Nullable<decimal> WindSpeed { get; set; }
        public Nullable<decimal> RainFallMm { get; set; }
        public Nullable<decimal> UvIndex { get; set; }
        public string WeatherType { get; set; }
        public string AllWeatherConditions { get; set; }
    
        public virtual WeatherType WeatherType1 { get; set; }
    }
}
